import Coulomb8.CoefficientBounds.B000

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column8 : Fin 102 → K := ![CoefficientBounds.p8,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p9,CoefficientBounds.p0,CoefficientBounds.p2,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p4,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes8 : Fin 102 → Dyadic := ![CoefficientBounds.b8,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b9,CoefficientBounds.b0,CoefficientBounds.b2,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b4,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds8 (r : Fin 102) : (boxes8 r).Contains (K.eval (column8 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound8
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound9
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound4
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column9 : Fin 102 → K := ![CoefficientBounds.p12,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p9,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p3,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p4,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes9 : Fin 102 → Dyadic := ![CoefficientBounds.b12,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b9,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b3,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b4,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds9 (r : Fin 102) : (boxes9 r).Contains (K.eval (column9 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound12
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound9
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound3
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound4
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column10 : Fin 102 → K := ![CoefficientBounds.p13,CoefficientBounds.p4,CoefficientBounds.p14,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p15,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes10 : Fin 102 → Dyadic := ![CoefficientBounds.b13,CoefficientBounds.b4,CoefficientBounds.b14,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b15,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds10 (r : Fin 102) : (boxes10 r).Contains (K.eval (column10 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound13
  · exact CoefficientBounds.sound4
  · exact CoefficientBounds.sound14
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound15
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column11 : Fin 102 → K := ![CoefficientBounds.p0,CoefficientBounds.p16,CoefficientBounds.p0,CoefficientBounds.p17,CoefficientBounds.p0,CoefficientBounds.p18,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p19,CoefficientBounds.p20,CoefficientBounds.p21,CoefficientBounds.p22,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes11 : Fin 102 → Dyadic := ![CoefficientBounds.b0,CoefficientBounds.b16,CoefficientBounds.b0,CoefficientBounds.b17,CoefficientBounds.b0,CoefficientBounds.b18,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b19,CoefficientBounds.b20,CoefficientBounds.b21,CoefficientBounds.b22,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds11 (r : Fin 102) : (boxes11 r).Contains (K.eval (column11 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound16
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound17
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound18
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound19
  · exact CoefficientBounds.sound20
  · exact CoefficientBounds.sound21
  · exact CoefficientBounds.sound22
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column12 : Fin 102 → K := ![CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2,CoefficientBounds.p0,CoefficientBounds.p23,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p4,CoefficientBounds.p15,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes12 : Fin 102 → Dyadic := ![CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2,CoefficientBounds.b0,CoefficientBounds.b23,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b4,CoefficientBounds.b15,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds12 (r : Fin 102) : (boxes12 r).Contains (K.eval (column12 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound23
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound4
  · exact CoefficientBounds.sound15
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column13 : Fin 102 → K := ![CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p24,CoefficientBounds.p16,CoefficientBounds.p25,CoefficientBounds.p26,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p27,CoefficientBounds.p28,CoefficientBounds.p20,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes13 : Fin 102 → Dyadic := ![CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b24,CoefficientBounds.b16,CoefficientBounds.b25,CoefficientBounds.b26,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b27,CoefficientBounds.b28,CoefficientBounds.b20,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds13 (r : Fin 102) : (boxes13 r).Contains (K.eval (column13 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound24
  · exact CoefficientBounds.sound16
  · exact CoefficientBounds.sound25
  · exact CoefficientBounds.sound26
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound27
  · exact CoefficientBounds.sound28
  · exact CoefficientBounds.sound20
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column14 : Fin 102 → K := ![CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p29,CoefficientBounds.p0,CoefficientBounds.p30,CoefficientBounds.p0,CoefficientBounds.p26,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p31,CoefficientBounds.p32,CoefficientBounds.p33,CoefficientBounds.p20,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes14 : Fin 102 → Dyadic := ![CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b29,CoefficientBounds.b0,CoefficientBounds.b30,CoefficientBounds.b0,CoefficientBounds.b26,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b31,CoefficientBounds.b32,CoefficientBounds.b33,CoefficientBounds.b20,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds14 (r : Fin 102) : (boxes14 r).Contains (K.eval (column14 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound29
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound30
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound26
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound31
  · exact CoefficientBounds.sound32
  · exact CoefficientBounds.sound33
  · exact CoefficientBounds.sound20
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column15 : Fin 102 → K := ![CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p34,CoefficientBounds.p0,CoefficientBounds.p35,CoefficientBounds.p0,CoefficientBounds.p36,CoefficientBounds.p0,CoefficientBounds.p37,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p38,CoefficientBounds.p0,CoefficientBounds.p39,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p40,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p41,CoefficientBounds.p0,CoefficientBounds.p42,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p43,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes15 : Fin 102 → Dyadic := ![CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b34,CoefficientBounds.b0,CoefficientBounds.b35,CoefficientBounds.b0,CoefficientBounds.b36,CoefficientBounds.b0,CoefficientBounds.b37,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b38,CoefficientBounds.b0,CoefficientBounds.b39,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b40,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b41,CoefficientBounds.b0,CoefficientBounds.b42,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b43,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds15 (r : Fin 102) : (boxes15 r).Contains (K.eval (column15 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound34
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound35
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound36
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound37
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound38
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound39
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound40
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound41
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound42
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound43
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
