import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B003
import Coulomb8.CoefficientBounds.B004
import Coulomb8.CoefficientBounds.B005
import Coulomb8.CoefficientBounds.B006
import Coulomb8.CoefficientBounds.B007

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column40 : Fin 102 → K := ![CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p299,CoefficientBounds.p0,CoefficientBounds.p300,CoefficientBounds.p0,CoefficientBounds.p301,CoefficientBounds.p0,CoefficientBounds.p302,CoefficientBounds.p0,CoefficientBounds.p303,CoefficientBounds.p0,CoefficientBounds.p252,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p304,CoefficientBounds.p0,CoefficientBounds.p305,CoefficientBounds.p0,CoefficientBounds.p284,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p306,CoefficientBounds.p0,CoefficientBounds.p287,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p260,CoefficientBounds.p307,CoefficientBounds.p0,CoefficientBounds.p308,CoefficientBounds.p0,CoefficientBounds.p291,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p309,CoefficientBounds.p0,CoefficientBounds.p294,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p268,CoefficientBounds.p0,CoefficientBounds.p310,CoefficientBounds.p0,CoefficientBounds.p296,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p271,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p311,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes40 : Fin 102 → Dyadic := ![CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b299,CoefficientBounds.b0,CoefficientBounds.b300,CoefficientBounds.b0,CoefficientBounds.b301,CoefficientBounds.b0,CoefficientBounds.b302,CoefficientBounds.b0,CoefficientBounds.b303,CoefficientBounds.b0,CoefficientBounds.b252,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b304,CoefficientBounds.b0,CoefficientBounds.b305,CoefficientBounds.b0,CoefficientBounds.b284,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b306,CoefficientBounds.b0,CoefficientBounds.b287,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b260,CoefficientBounds.b307,CoefficientBounds.b0,CoefficientBounds.b308,CoefficientBounds.b0,CoefficientBounds.b291,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b309,CoefficientBounds.b0,CoefficientBounds.b294,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b268,CoefficientBounds.b0,CoefficientBounds.b310,CoefficientBounds.b0,CoefficientBounds.b296,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b271,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b311,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds40 (r : Fin 102) : (boxes40 r).Contains (K.eval (column40 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound299
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound300
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound301
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound302
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound303
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound252
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound304
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound305
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound284
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound306
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound287
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound260
  · exact CoefficientBounds.sound307
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound308
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound291
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound309
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound294
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound268
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound310
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound296
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound271
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound311
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column41 : Fin 102 → K := ![CoefficientBounds.p312,CoefficientBounds.p313,CoefficientBounds.p314,CoefficientBounds.p315,CoefficientBounds.p316,CoefficientBounds.p317,CoefficientBounds.p318,CoefficientBounds.p319,CoefficientBounds.p320,CoefficientBounds.p321,CoefficientBounds.p322,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p323,CoefficientBounds.p324,CoefficientBounds.p325,CoefficientBounds.p326,CoefficientBounds.p323,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p327,CoefficientBounds.p317,CoefficientBounds.p328,CoefficientBounds.p329,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p260,CoefficientBounds.p329,CoefficientBounds.p330,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p331,CoefficientBounds.p332,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p323,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p333,CoefficientBounds.p334,CoefficientBounds.p335,CoefficientBounds.p336,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p337,CoefficientBounds.p338,CoefficientBounds.p339,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p340,CoefficientBounds.p341,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p339,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p342,CoefficientBounds.p343,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p344,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes41 : Fin 102 → Dyadic := ![CoefficientBounds.b312,CoefficientBounds.b313,CoefficientBounds.b314,CoefficientBounds.b315,CoefficientBounds.b316,CoefficientBounds.b317,CoefficientBounds.b318,CoefficientBounds.b319,CoefficientBounds.b320,CoefficientBounds.b321,CoefficientBounds.b322,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b323,CoefficientBounds.b324,CoefficientBounds.b325,CoefficientBounds.b326,CoefficientBounds.b323,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b327,CoefficientBounds.b317,CoefficientBounds.b328,CoefficientBounds.b329,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b260,CoefficientBounds.b329,CoefficientBounds.b330,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b331,CoefficientBounds.b332,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b323,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b333,CoefficientBounds.b334,CoefficientBounds.b335,CoefficientBounds.b336,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b337,CoefficientBounds.b338,CoefficientBounds.b339,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b340,CoefficientBounds.b341,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b339,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b342,CoefficientBounds.b343,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b344,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds41 (r : Fin 102) : (boxes41 r).Contains (K.eval (column41 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound312
  · exact CoefficientBounds.sound313
  · exact CoefficientBounds.sound314
  · exact CoefficientBounds.sound315
  · exact CoefficientBounds.sound316
  · exact CoefficientBounds.sound317
  · exact CoefficientBounds.sound318
  · exact CoefficientBounds.sound319
  · exact CoefficientBounds.sound320
  · exact CoefficientBounds.sound321
  · exact CoefficientBounds.sound322
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound323
  · exact CoefficientBounds.sound324
  · exact CoefficientBounds.sound325
  · exact CoefficientBounds.sound326
  · exact CoefficientBounds.sound323
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound327
  · exact CoefficientBounds.sound317
  · exact CoefficientBounds.sound328
  · exact CoefficientBounds.sound329
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound260
  · exact CoefficientBounds.sound329
  · exact CoefficientBounds.sound330
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound331
  · exact CoefficientBounds.sound332
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound323
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound333
  · exact CoefficientBounds.sound334
  · exact CoefficientBounds.sound335
  · exact CoefficientBounds.sound336
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound337
  · exact CoefficientBounds.sound338
  · exact CoefficientBounds.sound339
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound340
  · exact CoefficientBounds.sound341
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound339
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound342
  · exact CoefficientBounds.sound343
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound344
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column42 : Fin 102 → K := ![CoefficientBounds.p345,CoefficientBounds.p346,CoefficientBounds.p347,CoefficientBounds.p348,CoefficientBounds.p349,CoefficientBounds.p350,CoefficientBounds.p351,CoefficientBounds.p352,CoefficientBounds.p353,CoefficientBounds.p354,CoefficientBounds.p355,CoefficientBounds.p356,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p357,CoefficientBounds.p0,CoefficientBounds.p358,CoefficientBounds.p0,CoefficientBounds.p359,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p360,CoefficientBounds.p361,CoefficientBounds.p362,CoefficientBounds.p363,CoefficientBounds.p364,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p365,CoefficientBounds.p0,CoefficientBounds.p257,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p366,CoefficientBounds.p367,CoefficientBounds.p368,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p359,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p369,CoefficientBounds.p370,CoefficientBounds.p371,CoefficientBounds.p372,CoefficientBounds.p373,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p374,CoefficientBounds.p375,CoefficientBounds.p298,CoefficientBounds.p376,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p377,CoefficientBounds.p378,CoefficientBounds.p379,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p376,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p380,CoefficientBounds.p381,CoefficientBounds.p382,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p383,CoefficientBounds.p384,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes42 : Fin 102 → Dyadic := ![CoefficientBounds.b345,CoefficientBounds.b346,CoefficientBounds.b347,CoefficientBounds.b348,CoefficientBounds.b349,CoefficientBounds.b350,CoefficientBounds.b351,CoefficientBounds.b352,CoefficientBounds.b353,CoefficientBounds.b354,CoefficientBounds.b355,CoefficientBounds.b356,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b357,CoefficientBounds.b0,CoefficientBounds.b358,CoefficientBounds.b0,CoefficientBounds.b359,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b360,CoefficientBounds.b361,CoefficientBounds.b362,CoefficientBounds.b363,CoefficientBounds.b364,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b365,CoefficientBounds.b0,CoefficientBounds.b257,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b366,CoefficientBounds.b367,CoefficientBounds.b368,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b359,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b369,CoefficientBounds.b370,CoefficientBounds.b371,CoefficientBounds.b372,CoefficientBounds.b373,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b374,CoefficientBounds.b375,CoefficientBounds.b298,CoefficientBounds.b376,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b377,CoefficientBounds.b378,CoefficientBounds.b379,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b376,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b380,CoefficientBounds.b381,CoefficientBounds.b382,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b383,CoefficientBounds.b384,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds42 (r : Fin 102) : (boxes42 r).Contains (K.eval (column42 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound345
  · exact CoefficientBounds.sound346
  · exact CoefficientBounds.sound347
  · exact CoefficientBounds.sound348
  · exact CoefficientBounds.sound349
  · exact CoefficientBounds.sound350
  · exact CoefficientBounds.sound351
  · exact CoefficientBounds.sound352
  · exact CoefficientBounds.sound353
  · exact CoefficientBounds.sound354
  · exact CoefficientBounds.sound355
  · exact CoefficientBounds.sound356
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound357
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound358
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound359
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound360
  · exact CoefficientBounds.sound361
  · exact CoefficientBounds.sound362
  · exact CoefficientBounds.sound363
  · exact CoefficientBounds.sound364
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound365
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound257
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound366
  · exact CoefficientBounds.sound367
  · exact CoefficientBounds.sound368
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound359
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound369
  · exact CoefficientBounds.sound370
  · exact CoefficientBounds.sound371
  · exact CoefficientBounds.sound372
  · exact CoefficientBounds.sound373
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound374
  · exact CoefficientBounds.sound375
  · exact CoefficientBounds.sound298
  · exact CoefficientBounds.sound376
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound377
  · exact CoefficientBounds.sound378
  · exact CoefficientBounds.sound379
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound376
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound380
  · exact CoefficientBounds.sound381
  · exact CoefficientBounds.sound382
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound383
  · exact CoefficientBounds.sound384
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column43 : Fin 102 → K := ![CoefficientBounds.p385,CoefficientBounds.p0,CoefficientBounds.p386,CoefficientBounds.p0,CoefficientBounds.p387,CoefficientBounds.p0,CoefficientBounds.p388,CoefficientBounds.p0,CoefficientBounds.p389,CoefficientBounds.p0,CoefficientBounds.p390,CoefficientBounds.p0,CoefficientBounds.p356,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p391,CoefficientBounds.p0,CoefficientBounds.p392,CoefficientBounds.p0,CoefficientBounds.p393,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p394,CoefficientBounds.p0,CoefficientBounds.p395,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p396,CoefficientBounds.p397,CoefficientBounds.p0,CoefficientBounds.p398,CoefficientBounds.p0,CoefficientBounds.p399,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p400,CoefficientBounds.p0,CoefficientBounds.p401,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p402,CoefficientBounds.p0,CoefficientBounds.p403,CoefficientBounds.p0,CoefficientBounds.p404,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p405,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p406,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes43 : Fin 102 → Dyadic := ![CoefficientBounds.b385,CoefficientBounds.b0,CoefficientBounds.b386,CoefficientBounds.b0,CoefficientBounds.b387,CoefficientBounds.b0,CoefficientBounds.b388,CoefficientBounds.b0,CoefficientBounds.b389,CoefficientBounds.b0,CoefficientBounds.b390,CoefficientBounds.b0,CoefficientBounds.b356,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b391,CoefficientBounds.b0,CoefficientBounds.b392,CoefficientBounds.b0,CoefficientBounds.b393,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b394,CoefficientBounds.b0,CoefficientBounds.b395,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b396,CoefficientBounds.b397,CoefficientBounds.b0,CoefficientBounds.b398,CoefficientBounds.b0,CoefficientBounds.b399,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b400,CoefficientBounds.b0,CoefficientBounds.b401,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b402,CoefficientBounds.b0,CoefficientBounds.b403,CoefficientBounds.b0,CoefficientBounds.b404,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b405,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b406,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds43 (r : Fin 102) : (boxes43 r).Contains (K.eval (column43 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound385
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound386
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound387
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound388
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound389
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound390
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound356
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound391
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound392
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound393
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound394
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound395
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound396
  · exact CoefficientBounds.sound397
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound398
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound399
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound400
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound401
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound402
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound403
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound404
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound405
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound406
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column44 : Fin 102 → K := ![CoefficientBounds.p407,CoefficientBounds.p408,CoefficientBounds.p409,CoefficientBounds.p410,CoefficientBounds.p411,CoefficientBounds.p412,CoefficientBounds.p413,CoefficientBounds.p414,CoefficientBounds.p415,CoefficientBounds.p416,CoefficientBounds.p417,CoefficientBounds.p418,CoefficientBounds.p419,CoefficientBounds.p420,CoefficientBounds.p421,CoefficientBounds.p422,CoefficientBounds.p423,CoefficientBounds.p424,CoefficientBounds.p425,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p426,CoefficientBounds.p427,CoefficientBounds.p428,CoefficientBounds.p425,CoefficientBounds.p426,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p429,CoefficientBounds.p0,CoefficientBounds.p430,CoefficientBounds.p431,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p431,CoefficientBounds.p432,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p433,CoefficientBounds.p434,CoefficientBounds.p0,CoefficientBounds.p435,CoefficientBounds.p436,CoefficientBounds.p437,CoefficientBounds.p438,CoefficientBounds.p439,CoefficientBounds.p440,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p441,CoefficientBounds.p442,CoefficientBounds.p443,CoefficientBounds.p444,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p444,CoefficientBounds.p445,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p446,CoefficientBounds.p447,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p448,CoefficientBounds.p0,CoefficientBounds.p449,CoefficientBounds.p450,CoefficientBounds.p451,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p452,CoefficientBounds.p453,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p454,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p455,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes44 : Fin 102 → Dyadic := ![CoefficientBounds.b407,CoefficientBounds.b408,CoefficientBounds.b409,CoefficientBounds.b410,CoefficientBounds.b411,CoefficientBounds.b412,CoefficientBounds.b413,CoefficientBounds.b414,CoefficientBounds.b415,CoefficientBounds.b416,CoefficientBounds.b417,CoefficientBounds.b418,CoefficientBounds.b419,CoefficientBounds.b420,CoefficientBounds.b421,CoefficientBounds.b422,CoefficientBounds.b423,CoefficientBounds.b424,CoefficientBounds.b425,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b426,CoefficientBounds.b427,CoefficientBounds.b428,CoefficientBounds.b425,CoefficientBounds.b426,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b429,CoefficientBounds.b0,CoefficientBounds.b430,CoefficientBounds.b431,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b431,CoefficientBounds.b432,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b433,CoefficientBounds.b434,CoefficientBounds.b0,CoefficientBounds.b435,CoefficientBounds.b436,CoefficientBounds.b437,CoefficientBounds.b438,CoefficientBounds.b439,CoefficientBounds.b440,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b441,CoefficientBounds.b442,CoefficientBounds.b443,CoefficientBounds.b444,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b444,CoefficientBounds.b445,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b446,CoefficientBounds.b447,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b448,CoefficientBounds.b0,CoefficientBounds.b449,CoefficientBounds.b450,CoefficientBounds.b451,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b452,CoefficientBounds.b453,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b454,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b455,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds44 (r : Fin 102) : (boxes44 r).Contains (K.eval (column44 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound407
  · exact CoefficientBounds.sound408
  · exact CoefficientBounds.sound409
  · exact CoefficientBounds.sound410
  · exact CoefficientBounds.sound411
  · exact CoefficientBounds.sound412
  · exact CoefficientBounds.sound413
  · exact CoefficientBounds.sound414
  · exact CoefficientBounds.sound415
  · exact CoefficientBounds.sound416
  · exact CoefficientBounds.sound417
  · exact CoefficientBounds.sound418
  · exact CoefficientBounds.sound419
  · exact CoefficientBounds.sound420
  · exact CoefficientBounds.sound421
  · exact CoefficientBounds.sound422
  · exact CoefficientBounds.sound423
  · exact CoefficientBounds.sound424
  · exact CoefficientBounds.sound425
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound426
  · exact CoefficientBounds.sound427
  · exact CoefficientBounds.sound428
  · exact CoefficientBounds.sound425
  · exact CoefficientBounds.sound426
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound429
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound430
  · exact CoefficientBounds.sound431
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound431
  · exact CoefficientBounds.sound432
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound433
  · exact CoefficientBounds.sound434
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound435
  · exact CoefficientBounds.sound436
  · exact CoefficientBounds.sound437
  · exact CoefficientBounds.sound438
  · exact CoefficientBounds.sound439
  · exact CoefficientBounds.sound440
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound441
  · exact CoefficientBounds.sound442
  · exact CoefficientBounds.sound443
  · exact CoefficientBounds.sound444
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound444
  · exact CoefficientBounds.sound445
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound446
  · exact CoefficientBounds.sound447
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound448
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound449
  · exact CoefficientBounds.sound450
  · exact CoefficientBounds.sound451
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound452
  · exact CoefficientBounds.sound453
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound454
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound455
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column45 : Fin 102 → K := ![CoefficientBounds.p456,CoefficientBounds.p457,CoefficientBounds.p458,CoefficientBounds.p459,CoefficientBounds.p460,CoefficientBounds.p461,CoefficientBounds.p462,CoefficientBounds.p463,CoefficientBounds.p464,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p465,CoefficientBounds.p466,CoefficientBounds.p467,CoefficientBounds.p468,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p469,CoefficientBounds.p470,CoefficientBounds.p471,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p472,CoefficientBounds.p463,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p473,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes45 : Fin 102 → Dyadic := ![CoefficientBounds.b456,CoefficientBounds.b457,CoefficientBounds.b458,CoefficientBounds.b459,CoefficientBounds.b460,CoefficientBounds.b461,CoefficientBounds.b462,CoefficientBounds.b463,CoefficientBounds.b464,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b465,CoefficientBounds.b466,CoefficientBounds.b467,CoefficientBounds.b468,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b469,CoefficientBounds.b470,CoefficientBounds.b471,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b472,CoefficientBounds.b463,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b473,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds45 (r : Fin 102) : (boxes45 r).Contains (K.eval (column45 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound456
  · exact CoefficientBounds.sound457
  · exact CoefficientBounds.sound458
  · exact CoefficientBounds.sound459
  · exact CoefficientBounds.sound460
  · exact CoefficientBounds.sound461
  · exact CoefficientBounds.sound462
  · exact CoefficientBounds.sound463
  · exact CoefficientBounds.sound464
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound465
  · exact CoefficientBounds.sound466
  · exact CoefficientBounds.sound467
  · exact CoefficientBounds.sound468
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound469
  · exact CoefficientBounds.sound470
  · exact CoefficientBounds.sound471
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound472
  · exact CoefficientBounds.sound463
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound473
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column46 : Fin 102 → K := ![CoefficientBounds.p474,CoefficientBounds.p475,CoefficientBounds.p476,CoefficientBounds.p477,CoefficientBounds.p478,CoefficientBounds.p479,CoefficientBounds.p480,CoefficientBounds.p481,CoefficientBounds.p463,CoefficientBounds.p473,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p482,CoefficientBounds.p483,CoefficientBounds.p484,CoefficientBounds.p485,CoefficientBounds.p468,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p486,CoefficientBounds.p487,CoefficientBounds.p488,CoefficientBounds.p471,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p489,CoefficientBounds.p490,CoefficientBounds.p463,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p473,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes46 : Fin 102 → Dyadic := ![CoefficientBounds.b474,CoefficientBounds.b475,CoefficientBounds.b476,CoefficientBounds.b477,CoefficientBounds.b478,CoefficientBounds.b479,CoefficientBounds.b480,CoefficientBounds.b481,CoefficientBounds.b463,CoefficientBounds.b473,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b482,CoefficientBounds.b483,CoefficientBounds.b484,CoefficientBounds.b485,CoefficientBounds.b468,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b486,CoefficientBounds.b487,CoefficientBounds.b488,CoefficientBounds.b471,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b489,CoefficientBounds.b490,CoefficientBounds.b463,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b473,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds46 (r : Fin 102) : (boxes46 r).Contains (K.eval (column46 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound474
  · exact CoefficientBounds.sound475
  · exact CoefficientBounds.sound476
  · exact CoefficientBounds.sound477
  · exact CoefficientBounds.sound478
  · exact CoefficientBounds.sound479
  · exact CoefficientBounds.sound480
  · exact CoefficientBounds.sound481
  · exact CoefficientBounds.sound463
  · exact CoefficientBounds.sound473
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound482
  · exact CoefficientBounds.sound483
  · exact CoefficientBounds.sound484
  · exact CoefficientBounds.sound485
  · exact CoefficientBounds.sound468
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound486
  · exact CoefficientBounds.sound487
  · exact CoefficientBounds.sound488
  · exact CoefficientBounds.sound471
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound489
  · exact CoefficientBounds.sound490
  · exact CoefficientBounds.sound463
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound473
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column47 : Fin 102 → K := ![CoefficientBounds.p491,CoefficientBounds.p492,CoefficientBounds.p493,CoefficientBounds.p494,CoefficientBounds.p495,CoefficientBounds.p496,CoefficientBounds.p497,CoefficientBounds.p498,CoefficientBounds.p471,CoefficientBounds.p463,CoefficientBounds.p473,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p499,CoefficientBounds.p500,CoefficientBounds.p501,CoefficientBounds.p502,CoefficientBounds.p0,CoefficientBounds.p468,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p503,CoefficientBounds.p504,CoefficientBounds.p505,CoefficientBounds.p0,CoefficientBounds.p471,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p506,CoefficientBounds.p507,CoefficientBounds.p0,CoefficientBounds.p463,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p473,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes47 : Fin 102 → Dyadic := ![CoefficientBounds.b491,CoefficientBounds.b492,CoefficientBounds.b493,CoefficientBounds.b494,CoefficientBounds.b495,CoefficientBounds.b496,CoefficientBounds.b497,CoefficientBounds.b498,CoefficientBounds.b471,CoefficientBounds.b463,CoefficientBounds.b473,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b499,CoefficientBounds.b500,CoefficientBounds.b501,CoefficientBounds.b502,CoefficientBounds.b0,CoefficientBounds.b468,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b503,CoefficientBounds.b504,CoefficientBounds.b505,CoefficientBounds.b0,CoefficientBounds.b471,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b506,CoefficientBounds.b507,CoefficientBounds.b0,CoefficientBounds.b463,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b473,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds47 (r : Fin 102) : (boxes47 r).Contains (K.eval (column47 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound491
  · exact CoefficientBounds.sound492
  · exact CoefficientBounds.sound493
  · exact CoefficientBounds.sound494
  · exact CoefficientBounds.sound495
  · exact CoefficientBounds.sound496
  · exact CoefficientBounds.sound497
  · exact CoefficientBounds.sound498
  · exact CoefficientBounds.sound471
  · exact CoefficientBounds.sound463
  · exact CoefficientBounds.sound473
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound499
  · exact CoefficientBounds.sound500
  · exact CoefficientBounds.sound501
  · exact CoefficientBounds.sound502
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound468
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound503
  · exact CoefficientBounds.sound504
  · exact CoefficientBounds.sound505
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound471
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound506
  · exact CoefficientBounds.sound507
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound463
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound473
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
