import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B008
import Coulomb8.CoefficientBounds.B009
import Coulomb8.CoefficientBounds.B010
import Coulomb8.CoefficientBounds.B011
import Coulomb8.CoefficientBounds.B012
import Coulomb8.CoefficientBounds.B013
import Coulomb8.CoefficientBounds.B014
import Coulomb8.CoefficientBounds.B015

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column64 : Fin 102 → K := ![CoefficientBounds.p849,CoefficientBounds.p850,CoefficientBounds.p851,CoefficientBounds.p852,CoefficientBounds.p853,CoefficientBounds.p854,CoefficientBounds.p855,CoefficientBounds.p856,CoefficientBounds.p586,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p857,CoefficientBounds.p858,CoefficientBounds.p859,CoefficientBounds.p860,CoefficientBounds.p861,CoefficientBounds.p591,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p862,CoefficientBounds.p863,CoefficientBounds.p804,CoefficientBounds.p864,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p865,CoefficientBounds.p0,CoefficientBounds.p586,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p866,CoefficientBounds.p867,CoefficientBounds.p860,CoefficientBounds.p0,CoefficientBounds.p591,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p847,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p868,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes64 : Fin 102 → Dyadic := ![CoefficientBounds.b849,CoefficientBounds.b850,CoefficientBounds.b851,CoefficientBounds.b852,CoefficientBounds.b853,CoefficientBounds.b854,CoefficientBounds.b855,CoefficientBounds.b856,CoefficientBounds.b586,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b857,CoefficientBounds.b858,CoefficientBounds.b859,CoefficientBounds.b860,CoefficientBounds.b861,CoefficientBounds.b591,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b862,CoefficientBounds.b863,CoefficientBounds.b804,CoefficientBounds.b864,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b865,CoefficientBounds.b0,CoefficientBounds.b586,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b866,CoefficientBounds.b867,CoefficientBounds.b860,CoefficientBounds.b0,CoefficientBounds.b591,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b847,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b868,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds64 (r : Fin 102) : (boxes64 r).Contains (K.eval (column64 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound849
  · exact CoefficientBounds.sound850
  · exact CoefficientBounds.sound851
  · exact CoefficientBounds.sound852
  · exact CoefficientBounds.sound853
  · exact CoefficientBounds.sound854
  · exact CoefficientBounds.sound855
  · exact CoefficientBounds.sound856
  · exact CoefficientBounds.sound586
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound857
  · exact CoefficientBounds.sound858
  · exact CoefficientBounds.sound859
  · exact CoefficientBounds.sound860
  · exact CoefficientBounds.sound861
  · exact CoefficientBounds.sound591
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound862
  · exact CoefficientBounds.sound863
  · exact CoefficientBounds.sound804
  · exact CoefficientBounds.sound864
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound865
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound586
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound866
  · exact CoefficientBounds.sound867
  · exact CoefficientBounds.sound860
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound591
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound847
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound868
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column65 : Fin 102 → K := ![CoefficientBounds.p869,CoefficientBounds.p870,CoefficientBounds.p871,CoefficientBounds.p872,CoefficientBounds.p873,CoefficientBounds.p874,CoefficientBounds.p875,CoefficientBounds.p876,CoefficientBounds.p608,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p877,CoefficientBounds.p878,CoefficientBounds.p879,CoefficientBounds.p880,CoefficientBounds.p881,CoefficientBounds.p613,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p882,CoefficientBounds.p883,CoefficientBounds.p842,CoefficientBounds.p884,CoefficientBounds.p799,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p885,CoefficientBounds.p824,CoefficientBounds.p886,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p887,CoefficientBounds.p888,CoefficientBounds.p880,CoefficientBounds.p0,CoefficientBounds.p613,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p842,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p804,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes65 : Fin 102 → Dyadic := ![CoefficientBounds.b869,CoefficientBounds.b870,CoefficientBounds.b871,CoefficientBounds.b872,CoefficientBounds.b873,CoefficientBounds.b874,CoefficientBounds.b875,CoefficientBounds.b876,CoefficientBounds.b608,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b877,CoefficientBounds.b878,CoefficientBounds.b879,CoefficientBounds.b880,CoefficientBounds.b881,CoefficientBounds.b613,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b882,CoefficientBounds.b883,CoefficientBounds.b842,CoefficientBounds.b884,CoefficientBounds.b799,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b885,CoefficientBounds.b824,CoefficientBounds.b886,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b887,CoefficientBounds.b888,CoefficientBounds.b880,CoefficientBounds.b0,CoefficientBounds.b613,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b842,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b804,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds65 (r : Fin 102) : (boxes65 r).Contains (K.eval (column65 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound869
  · exact CoefficientBounds.sound870
  · exact CoefficientBounds.sound871
  · exact CoefficientBounds.sound872
  · exact CoefficientBounds.sound873
  · exact CoefficientBounds.sound874
  · exact CoefficientBounds.sound875
  · exact CoefficientBounds.sound876
  · exact CoefficientBounds.sound608
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound877
  · exact CoefficientBounds.sound878
  · exact CoefficientBounds.sound879
  · exact CoefficientBounds.sound880
  · exact CoefficientBounds.sound881
  · exact CoefficientBounds.sound613
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound882
  · exact CoefficientBounds.sound883
  · exact CoefficientBounds.sound842
  · exact CoefficientBounds.sound884
  · exact CoefficientBounds.sound799
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound885
  · exact CoefficientBounds.sound824
  · exact CoefficientBounds.sound886
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound887
  · exact CoefficientBounds.sound888
  · exact CoefficientBounds.sound880
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound613
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound842
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound804
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column66 : Fin 102 → K := ![CoefficientBounds.p889,CoefficientBounds.p890,CoefficientBounds.p891,CoefficientBounds.p892,CoefficientBounds.p893,CoefficientBounds.p894,CoefficientBounds.p895,CoefficientBounds.p896,CoefficientBounds.p630,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p897,CoefficientBounds.p898,CoefficientBounds.p899,CoefficientBounds.p900,CoefficientBounds.p901,CoefficientBounds.p635,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p902,CoefficientBounds.p903,CoefficientBounds.p904,CoefficientBounds.p905,CoefficientBounds.p804,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p906,CoefficientBounds.p847,CoefficientBounds.p630,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p907,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p908,CoefficientBounds.p909,CoefficientBounds.p900,CoefficientBounds.p0,CoefficientBounds.p635,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p847,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p907,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes66 : Fin 102 → Dyadic := ![CoefficientBounds.b889,CoefficientBounds.b890,CoefficientBounds.b891,CoefficientBounds.b892,CoefficientBounds.b893,CoefficientBounds.b894,CoefficientBounds.b895,CoefficientBounds.b896,CoefficientBounds.b630,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b897,CoefficientBounds.b898,CoefficientBounds.b899,CoefficientBounds.b900,CoefficientBounds.b901,CoefficientBounds.b635,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b902,CoefficientBounds.b903,CoefficientBounds.b904,CoefficientBounds.b905,CoefficientBounds.b804,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b906,CoefficientBounds.b847,CoefficientBounds.b630,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b907,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b908,CoefficientBounds.b909,CoefficientBounds.b900,CoefficientBounds.b0,CoefficientBounds.b635,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b847,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b907,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds66 (r : Fin 102) : (boxes66 r).Contains (K.eval (column66 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound889
  · exact CoefficientBounds.sound890
  · exact CoefficientBounds.sound891
  · exact CoefficientBounds.sound892
  · exact CoefficientBounds.sound893
  · exact CoefficientBounds.sound894
  · exact CoefficientBounds.sound895
  · exact CoefficientBounds.sound896
  · exact CoefficientBounds.sound630
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound897
  · exact CoefficientBounds.sound898
  · exact CoefficientBounds.sound899
  · exact CoefficientBounds.sound900
  · exact CoefficientBounds.sound901
  · exact CoefficientBounds.sound635
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound902
  · exact CoefficientBounds.sound903
  · exact CoefficientBounds.sound904
  · exact CoefficientBounds.sound905
  · exact CoefficientBounds.sound804
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound906
  · exact CoefficientBounds.sound847
  · exact CoefficientBounds.sound630
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound907
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound908
  · exact CoefficientBounds.sound909
  · exact CoefficientBounds.sound900
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound635
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound847
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound907
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column67 : Fin 102 → K := ![CoefficientBounds.p910,CoefficientBounds.p911,CoefficientBounds.p912,CoefficientBounds.p913,CoefficientBounds.p914,CoefficientBounds.p915,CoefficientBounds.p916,CoefficientBounds.p661,CoefficientBounds.p653,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p917,CoefficientBounds.p918,CoefficientBounds.p919,CoefficientBounds.p920,CoefficientBounds.p921,CoefficientBounds.p658,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p922,CoefficientBounds.p923,CoefficientBounds.p0,CoefficientBounds.p661,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p924,CoefficientBounds.p847,CoefficientBounds.p925,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p926,CoefficientBounds.p927,CoefficientBounds.p920,CoefficientBounds.p0,CoefficientBounds.p658,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p847,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p804,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p928,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes67 : Fin 102 → Dyadic := ![CoefficientBounds.b910,CoefficientBounds.b911,CoefficientBounds.b912,CoefficientBounds.b913,CoefficientBounds.b914,CoefficientBounds.b915,CoefficientBounds.b916,CoefficientBounds.b661,CoefficientBounds.b653,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b917,CoefficientBounds.b918,CoefficientBounds.b919,CoefficientBounds.b920,CoefficientBounds.b921,CoefficientBounds.b658,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b922,CoefficientBounds.b923,CoefficientBounds.b0,CoefficientBounds.b661,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b924,CoefficientBounds.b847,CoefficientBounds.b925,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b926,CoefficientBounds.b927,CoefficientBounds.b920,CoefficientBounds.b0,CoefficientBounds.b658,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b847,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b804,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b928,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds67 (r : Fin 102) : (boxes67 r).Contains (K.eval (column67 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound910
  · exact CoefficientBounds.sound911
  · exact CoefficientBounds.sound912
  · exact CoefficientBounds.sound913
  · exact CoefficientBounds.sound914
  · exact CoefficientBounds.sound915
  · exact CoefficientBounds.sound916
  · exact CoefficientBounds.sound661
  · exact CoefficientBounds.sound653
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound917
  · exact CoefficientBounds.sound918
  · exact CoefficientBounds.sound919
  · exact CoefficientBounds.sound920
  · exact CoefficientBounds.sound921
  · exact CoefficientBounds.sound658
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound922
  · exact CoefficientBounds.sound923
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound661
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound924
  · exact CoefficientBounds.sound847
  · exact CoefficientBounds.sound925
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound926
  · exact CoefficientBounds.sound927
  · exact CoefficientBounds.sound920
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound658
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound847
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound804
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound928
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column68 : Fin 102 → K := ![CoefficientBounds.p929,CoefficientBounds.p930,CoefficientBounds.p931,CoefficientBounds.p932,CoefficientBounds.p933,CoefficientBounds.p934,CoefficientBounds.p935,CoefficientBounds.p683,CoefficientBounds.p675,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p936,CoefficientBounds.p937,CoefficientBounds.p938,CoefficientBounds.p939,CoefficientBounds.p940,CoefficientBounds.p680,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p941,CoefficientBounds.p942,CoefficientBounds.p0,CoefficientBounds.p683,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p943,CoefficientBounds.p0,CoefficientBounds.p675,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p944,CoefficientBounds.p945,CoefficientBounds.p946,CoefficientBounds.p947,CoefficientBounds.p680,CoefficientBounds.p689,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes68 : Fin 102 → Dyadic := ![CoefficientBounds.b929,CoefficientBounds.b930,CoefficientBounds.b931,CoefficientBounds.b932,CoefficientBounds.b933,CoefficientBounds.b934,CoefficientBounds.b935,CoefficientBounds.b683,CoefficientBounds.b675,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b936,CoefficientBounds.b937,CoefficientBounds.b938,CoefficientBounds.b939,CoefficientBounds.b940,CoefficientBounds.b680,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b941,CoefficientBounds.b942,CoefficientBounds.b0,CoefficientBounds.b683,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b943,CoefficientBounds.b0,CoefficientBounds.b675,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b944,CoefficientBounds.b945,CoefficientBounds.b946,CoefficientBounds.b947,CoefficientBounds.b680,CoefficientBounds.b689,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds68 (r : Fin 102) : (boxes68 r).Contains (K.eval (column68 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound929
  · exact CoefficientBounds.sound930
  · exact CoefficientBounds.sound931
  · exact CoefficientBounds.sound932
  · exact CoefficientBounds.sound933
  · exact CoefficientBounds.sound934
  · exact CoefficientBounds.sound935
  · exact CoefficientBounds.sound683
  · exact CoefficientBounds.sound675
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound936
  · exact CoefficientBounds.sound937
  · exact CoefficientBounds.sound938
  · exact CoefficientBounds.sound939
  · exact CoefficientBounds.sound940
  · exact CoefficientBounds.sound680
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound941
  · exact CoefficientBounds.sound942
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound683
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound943
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound675
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound944
  · exact CoefficientBounds.sound945
  · exact CoefficientBounds.sound946
  · exact CoefficientBounds.sound947
  · exact CoefficientBounds.sound680
  · exact CoefficientBounds.sound689
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column69 : Fin 102 → K := ![CoefficientBounds.p948,CoefficientBounds.p949,CoefficientBounds.p950,CoefficientBounds.p951,CoefficientBounds.p952,CoefficientBounds.p953,CoefficientBounds.p954,CoefficientBounds.p705,CoefficientBounds.p697,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p955,CoefficientBounds.p956,CoefficientBounds.p957,CoefficientBounds.p958,CoefficientBounds.p959,CoefficientBounds.p702,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p960,CoefficientBounds.p961,CoefficientBounds.p0,CoefficientBounds.p705,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p962,CoefficientBounds.p0,CoefficientBounds.p697,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p963,CoefficientBounds.p964,CoefficientBounds.p965,CoefficientBounds.p804,CoefficientBounds.p966,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p967,CoefficientBounds.p804,CoefficientBounds.p825,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes69 : Fin 102 → Dyadic := ![CoefficientBounds.b948,CoefficientBounds.b949,CoefficientBounds.b950,CoefficientBounds.b951,CoefficientBounds.b952,CoefficientBounds.b953,CoefficientBounds.b954,CoefficientBounds.b705,CoefficientBounds.b697,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b955,CoefficientBounds.b956,CoefficientBounds.b957,CoefficientBounds.b958,CoefficientBounds.b959,CoefficientBounds.b702,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b960,CoefficientBounds.b961,CoefficientBounds.b0,CoefficientBounds.b705,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b962,CoefficientBounds.b0,CoefficientBounds.b697,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b963,CoefficientBounds.b964,CoefficientBounds.b965,CoefficientBounds.b804,CoefficientBounds.b966,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b967,CoefficientBounds.b804,CoefficientBounds.b825,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds69 (r : Fin 102) : (boxes69 r).Contains (K.eval (column69 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound948
  · exact CoefficientBounds.sound949
  · exact CoefficientBounds.sound950
  · exact CoefficientBounds.sound951
  · exact CoefficientBounds.sound952
  · exact CoefficientBounds.sound953
  · exact CoefficientBounds.sound954
  · exact CoefficientBounds.sound705
  · exact CoefficientBounds.sound697
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound955
  · exact CoefficientBounds.sound956
  · exact CoefficientBounds.sound957
  · exact CoefficientBounds.sound958
  · exact CoefficientBounds.sound959
  · exact CoefficientBounds.sound702
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound960
  · exact CoefficientBounds.sound961
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound705
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound962
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound697
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound963
  · exact CoefficientBounds.sound964
  · exact CoefficientBounds.sound965
  · exact CoefficientBounds.sound804
  · exact CoefficientBounds.sound966
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound967
  · exact CoefficientBounds.sound804
  · exact CoefficientBounds.sound825
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column70 : Fin 102 → K := ![CoefficientBounds.p968,CoefficientBounds.p969,CoefficientBounds.p970,CoefficientBounds.p971,CoefficientBounds.p972,CoefficientBounds.p973,CoefficientBounds.p974,CoefficientBounds.p726,CoefficientBounds.p719,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p975,CoefficientBounds.p976,CoefficientBounds.p977,CoefficientBounds.p0,CoefficientBounds.p723,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p978,CoefficientBounds.p979,CoefficientBounds.p0,CoefficientBounds.p726,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p980,CoefficientBounds.p0,CoefficientBounds.p719,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p981,CoefficientBounds.p967,CoefficientBounds.p907,CoefficientBounds.p982,CoefficientBounds.p0,CoefficientBounds.p645,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p983,CoefficientBounds.p907,CoefficientBounds.p982,CoefficientBounds.p0,CoefficientBounds.p645,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes70 : Fin 102 → Dyadic := ![CoefficientBounds.b968,CoefficientBounds.b969,CoefficientBounds.b970,CoefficientBounds.b971,CoefficientBounds.b972,CoefficientBounds.b973,CoefficientBounds.b974,CoefficientBounds.b726,CoefficientBounds.b719,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b975,CoefficientBounds.b976,CoefficientBounds.b977,CoefficientBounds.b0,CoefficientBounds.b723,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b978,CoefficientBounds.b979,CoefficientBounds.b0,CoefficientBounds.b726,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b980,CoefficientBounds.b0,CoefficientBounds.b719,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b981,CoefficientBounds.b967,CoefficientBounds.b907,CoefficientBounds.b982,CoefficientBounds.b0,CoefficientBounds.b645,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b983,CoefficientBounds.b907,CoefficientBounds.b982,CoefficientBounds.b0,CoefficientBounds.b645,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds70 (r : Fin 102) : (boxes70 r).Contains (K.eval (column70 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound968
  · exact CoefficientBounds.sound969
  · exact CoefficientBounds.sound970
  · exact CoefficientBounds.sound971
  · exact CoefficientBounds.sound972
  · exact CoefficientBounds.sound973
  · exact CoefficientBounds.sound974
  · exact CoefficientBounds.sound726
  · exact CoefficientBounds.sound719
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound975
  · exact CoefficientBounds.sound976
  · exact CoefficientBounds.sound977
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound723
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound978
  · exact CoefficientBounds.sound979
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound726
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound980
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound719
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound981
  · exact CoefficientBounds.sound967
  · exact CoefficientBounds.sound907
  · exact CoefficientBounds.sound982
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound645
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound983
  · exact CoefficientBounds.sound907
  · exact CoefficientBounds.sound982
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound645
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column71 : Fin 102 → K := ![CoefficientBounds.p984,CoefficientBounds.p985,CoefficientBounds.p986,CoefficientBounds.p987,CoefficientBounds.p988,CoefficientBounds.p989,CoefficientBounds.p990,CoefficientBounds.p746,CoefficientBounds.p738,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p991,CoefficientBounds.p992,CoefficientBounds.p993,CoefficientBounds.p994,CoefficientBounds.p995,CoefficientBounds.p743,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p996,CoefficientBounds.p997,CoefficientBounds.p0,CoefficientBounds.p746,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p998,CoefficientBounds.p0,CoefficientBounds.p738,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p999,CoefficientBounds.p1000,CoefficientBounds.p994,CoefficientBounds.p0,CoefficientBounds.p743,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1001,CoefficientBounds.p1002,CoefficientBounds.p1003,CoefficientBounds.p1004,CoefficientBounds.p0,CoefficientBounds.p755,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes71 : Fin 102 → Dyadic := ![CoefficientBounds.b984,CoefficientBounds.b985,CoefficientBounds.b986,CoefficientBounds.b987,CoefficientBounds.b988,CoefficientBounds.b989,CoefficientBounds.b990,CoefficientBounds.b746,CoefficientBounds.b738,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b991,CoefficientBounds.b992,CoefficientBounds.b993,CoefficientBounds.b994,CoefficientBounds.b995,CoefficientBounds.b743,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b996,CoefficientBounds.b997,CoefficientBounds.b0,CoefficientBounds.b746,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b998,CoefficientBounds.b0,CoefficientBounds.b738,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b999,CoefficientBounds.b1000,CoefficientBounds.b994,CoefficientBounds.b0,CoefficientBounds.b743,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1001,CoefficientBounds.b1002,CoefficientBounds.b1003,CoefficientBounds.b1004,CoefficientBounds.b0,CoefficientBounds.b755,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds71 (r : Fin 102) : (boxes71 r).Contains (K.eval (column71 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound984
  · exact CoefficientBounds.sound985
  · exact CoefficientBounds.sound986
  · exact CoefficientBounds.sound987
  · exact CoefficientBounds.sound988
  · exact CoefficientBounds.sound989
  · exact CoefficientBounds.sound990
  · exact CoefficientBounds.sound746
  · exact CoefficientBounds.sound738
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound991
  · exact CoefficientBounds.sound992
  · exact CoefficientBounds.sound993
  · exact CoefficientBounds.sound994
  · exact CoefficientBounds.sound995
  · exact CoefficientBounds.sound743
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound996
  · exact CoefficientBounds.sound997
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound746
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound998
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound738
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound999
  · exact CoefficientBounds.sound1000
  · exact CoefficientBounds.sound994
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound743
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1001
  · exact CoefficientBounds.sound1002
  · exact CoefficientBounds.sound1003
  · exact CoefficientBounds.sound1004
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound755
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
