import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B007
import Coulomb8.CoefficientBounds.B008
import Coulomb8.CoefficientBounds.B009
import Coulomb8.CoefficientBounds.B010
import Coulomb8.CoefficientBounds.B012
import Coulomb8.CoefficientBounds.B013
import Coulomb8.CoefficientBounds.B014
import Coulomb8.CoefficientBounds.B015
import Coulomb8.CoefficientBounds.B016
import Coulomb8.CoefficientBounds.B017

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column72 : Fin 102 → K := ![CoefficientBounds.p1005,CoefficientBounds.p1006,CoefficientBounds.p1007,CoefficientBounds.p1008,CoefficientBounds.p1009,CoefficientBounds.p1010,CoefficientBounds.p1011,CoefficientBounds.p502,CoefficientBounds.p505,CoefficientBounds.p507,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p464,CoefficientBounds.p1012,CoefficientBounds.p1013,CoefficientBounds.p1014,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p502,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1015,CoefficientBounds.p1010,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p505,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1016,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p507,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p473,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes72 : Fin 102 → Dyadic := ![CoefficientBounds.b1005,CoefficientBounds.b1006,CoefficientBounds.b1007,CoefficientBounds.b1008,CoefficientBounds.b1009,CoefficientBounds.b1010,CoefficientBounds.b1011,CoefficientBounds.b502,CoefficientBounds.b505,CoefficientBounds.b507,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b464,CoefficientBounds.b1012,CoefficientBounds.b1013,CoefficientBounds.b1014,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b502,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1015,CoefficientBounds.b1010,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b505,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1016,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b507,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b473,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds72 (r : Fin 102) : (boxes72 r).Contains (K.eval (column72 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1005
  · exact CoefficientBounds.sound1006
  · exact CoefficientBounds.sound1007
  · exact CoefficientBounds.sound1008
  · exact CoefficientBounds.sound1009
  · exact CoefficientBounds.sound1010
  · exact CoefficientBounds.sound1011
  · exact CoefficientBounds.sound502
  · exact CoefficientBounds.sound505
  · exact CoefficientBounds.sound507
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound464
  · exact CoefficientBounds.sound1012
  · exact CoefficientBounds.sound1013
  · exact CoefficientBounds.sound1014
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound502
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1015
  · exact CoefficientBounds.sound1010
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound505
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1016
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound507
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound473
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column73 : Fin 102 → K := ![CoefficientBounds.p1017,CoefficientBounds.p1018,CoefficientBounds.p1019,CoefficientBounds.p1020,CoefficientBounds.p1021,CoefficientBounds.p1022,CoefficientBounds.p1023,CoefficientBounds.p1024,CoefficientBounds.p791,CoefficientBounds.p515,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1025,CoefficientBounds.p1026,CoefficientBounds.p1027,CoefficientBounds.p1028,CoefficientBounds.p1029,CoefficientBounds.p1024,CoefficientBounds.p529,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1030,CoefficientBounds.p1031,CoefficientBounds.p1029,CoefficientBounds.p0,CoefficientBounds.p791,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1032,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p515,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1033,CoefficientBounds.p1034,CoefficientBounds.p1035,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p529,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1036,CoefficientBounds.p1029,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes73 : Fin 102 → Dyadic := ![CoefficientBounds.b1017,CoefficientBounds.b1018,CoefficientBounds.b1019,CoefficientBounds.b1020,CoefficientBounds.b1021,CoefficientBounds.b1022,CoefficientBounds.b1023,CoefficientBounds.b1024,CoefficientBounds.b791,CoefficientBounds.b515,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1025,CoefficientBounds.b1026,CoefficientBounds.b1027,CoefficientBounds.b1028,CoefficientBounds.b1029,CoefficientBounds.b1024,CoefficientBounds.b529,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1030,CoefficientBounds.b1031,CoefficientBounds.b1029,CoefficientBounds.b0,CoefficientBounds.b791,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1032,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b515,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1033,CoefficientBounds.b1034,CoefficientBounds.b1035,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b529,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1036,CoefficientBounds.b1029,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds73 (r : Fin 102) : (boxes73 r).Contains (K.eval (column73 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1017
  · exact CoefficientBounds.sound1018
  · exact CoefficientBounds.sound1019
  · exact CoefficientBounds.sound1020
  · exact CoefficientBounds.sound1021
  · exact CoefficientBounds.sound1022
  · exact CoefficientBounds.sound1023
  · exact CoefficientBounds.sound1024
  · exact CoefficientBounds.sound791
  · exact CoefficientBounds.sound515
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1025
  · exact CoefficientBounds.sound1026
  · exact CoefficientBounds.sound1027
  · exact CoefficientBounds.sound1028
  · exact CoefficientBounds.sound1029
  · exact CoefficientBounds.sound1024
  · exact CoefficientBounds.sound529
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1030
  · exact CoefficientBounds.sound1031
  · exact CoefficientBounds.sound1029
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound791
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1032
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound515
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1033
  · exact CoefficientBounds.sound1034
  · exact CoefficientBounds.sound1035
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound529
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1036
  · exact CoefficientBounds.sound1029
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column74 : Fin 102 → K := ![CoefficientBounds.p1037,CoefficientBounds.p1038,CoefficientBounds.p1039,CoefficientBounds.p1040,CoefficientBounds.p1041,CoefficientBounds.p1042,CoefficientBounds.p1043,CoefficientBounds.p1044,CoefficientBounds.p547,CoefficientBounds.p539,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1045,CoefficientBounds.p1046,CoefficientBounds.p1047,CoefficientBounds.p1048,CoefficientBounds.p1049,CoefficientBounds.p1050,CoefficientBounds.p553,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1051,CoefficientBounds.p1052,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p547,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1053,CoefficientBounds.p1029,CoefficientBounds.p0,CoefficientBounds.p539,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1054,CoefficientBounds.p1055,CoefficientBounds.p1056,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p553,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1049,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes74 : Fin 102 → Dyadic := ![CoefficientBounds.b1037,CoefficientBounds.b1038,CoefficientBounds.b1039,CoefficientBounds.b1040,CoefficientBounds.b1041,CoefficientBounds.b1042,CoefficientBounds.b1043,CoefficientBounds.b1044,CoefficientBounds.b547,CoefficientBounds.b539,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1045,CoefficientBounds.b1046,CoefficientBounds.b1047,CoefficientBounds.b1048,CoefficientBounds.b1049,CoefficientBounds.b1050,CoefficientBounds.b553,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1051,CoefficientBounds.b1052,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b547,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1053,CoefficientBounds.b1029,CoefficientBounds.b0,CoefficientBounds.b539,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1054,CoefficientBounds.b1055,CoefficientBounds.b1056,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b553,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1049,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds74 (r : Fin 102) : (boxes74 r).Contains (K.eval (column74 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1037
  · exact CoefficientBounds.sound1038
  · exact CoefficientBounds.sound1039
  · exact CoefficientBounds.sound1040
  · exact CoefficientBounds.sound1041
  · exact CoefficientBounds.sound1042
  · exact CoefficientBounds.sound1043
  · exact CoefficientBounds.sound1044
  · exact CoefficientBounds.sound547
  · exact CoefficientBounds.sound539
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1045
  · exact CoefficientBounds.sound1046
  · exact CoefficientBounds.sound1047
  · exact CoefficientBounds.sound1048
  · exact CoefficientBounds.sound1049
  · exact CoefficientBounds.sound1050
  · exact CoefficientBounds.sound553
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1051
  · exact CoefficientBounds.sound1052
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound547
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1053
  · exact CoefficientBounds.sound1029
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound539
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1054
  · exact CoefficientBounds.sound1055
  · exact CoefficientBounds.sound1056
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound553
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1049
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column75 : Fin 102 → K := ![CoefficientBounds.p1058,CoefficientBounds.p1059,CoefficientBounds.p1060,CoefficientBounds.p1061,CoefficientBounds.p1062,CoefficientBounds.p1063,CoefficientBounds.p1064,CoefficientBounds.p1065,CoefficientBounds.p833,CoefficientBounds.p563,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1066,CoefficientBounds.p1067,CoefficientBounds.p1068,CoefficientBounds.p1069,CoefficientBounds.p1070,CoefficientBounds.p1071,CoefficientBounds.p1072,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p1073,CoefficientBounds.p1063,CoefficientBounds.p1070,CoefficientBounds.p0,CoefficientBounds.p833,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1074,CoefficientBounds.p1049,CoefficientBounds.p0,CoefficientBounds.p563,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1075,CoefficientBounds.p1076,CoefficientBounds.p1077,CoefficientBounds.p1078,CoefficientBounds.p0,CoefficientBounds.p848,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1049,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1029,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes75 : Fin 102 → Dyadic := ![CoefficientBounds.b1058,CoefficientBounds.b1059,CoefficientBounds.b1060,CoefficientBounds.b1061,CoefficientBounds.b1062,CoefficientBounds.b1063,CoefficientBounds.b1064,CoefficientBounds.b1065,CoefficientBounds.b833,CoefficientBounds.b563,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1066,CoefficientBounds.b1067,CoefficientBounds.b1068,CoefficientBounds.b1069,CoefficientBounds.b1070,CoefficientBounds.b1071,CoefficientBounds.b1072,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b1073,CoefficientBounds.b1063,CoefficientBounds.b1070,CoefficientBounds.b0,CoefficientBounds.b833,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1074,CoefficientBounds.b1049,CoefficientBounds.b0,CoefficientBounds.b563,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1075,CoefficientBounds.b1076,CoefficientBounds.b1077,CoefficientBounds.b1078,CoefficientBounds.b0,CoefficientBounds.b848,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1049,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1029,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds75 (r : Fin 102) : (boxes75 r).Contains (K.eval (column75 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1058
  · exact CoefficientBounds.sound1059
  · exact CoefficientBounds.sound1060
  · exact CoefficientBounds.sound1061
  · exact CoefficientBounds.sound1062
  · exact CoefficientBounds.sound1063
  · exact CoefficientBounds.sound1064
  · exact CoefficientBounds.sound1065
  · exact CoefficientBounds.sound833
  · exact CoefficientBounds.sound563
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1066
  · exact CoefficientBounds.sound1067
  · exact CoefficientBounds.sound1068
  · exact CoefficientBounds.sound1069
  · exact CoefficientBounds.sound1070
  · exact CoefficientBounds.sound1071
  · exact CoefficientBounds.sound1072
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1073
  · exact CoefficientBounds.sound1063
  · exact CoefficientBounds.sound1070
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound833
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1074
  · exact CoefficientBounds.sound1049
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound563
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1075
  · exact CoefficientBounds.sound1076
  · exact CoefficientBounds.sound1077
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound848
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1049
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1029
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column76 : Fin 102 → K := ![CoefficientBounds.p1079,CoefficientBounds.p1080,CoefficientBounds.p1081,CoefficientBounds.p1082,CoefficientBounds.p1083,CoefficientBounds.p1084,CoefficientBounds.p1085,CoefficientBounds.p861,CoefficientBounds.p856,CoefficientBounds.p586,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1086,CoefficientBounds.p1087,CoefficientBounds.p1088,CoefficientBounds.p1089,CoefficientBounds.p0,CoefficientBounds.p861,CoefficientBounds.p591,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1090,CoefficientBounds.p1091,CoefficientBounds.p1036,CoefficientBounds.p1057,CoefficientBounds.p856,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1092,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p586,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1093,CoefficientBounds.p1094,CoefficientBounds.p1089,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p591,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1078,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1095,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes76 : Fin 102 → Dyadic := ![CoefficientBounds.b1079,CoefficientBounds.b1080,CoefficientBounds.b1081,CoefficientBounds.b1082,CoefficientBounds.b1083,CoefficientBounds.b1084,CoefficientBounds.b1085,CoefficientBounds.b861,CoefficientBounds.b856,CoefficientBounds.b586,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1086,CoefficientBounds.b1087,CoefficientBounds.b1088,CoefficientBounds.b1089,CoefficientBounds.b0,CoefficientBounds.b861,CoefficientBounds.b591,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1090,CoefficientBounds.b1091,CoefficientBounds.b1036,CoefficientBounds.b1057,CoefficientBounds.b856,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1092,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b586,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1093,CoefficientBounds.b1094,CoefficientBounds.b1089,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b591,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1078,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1095,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds76 (r : Fin 102) : (boxes76 r).Contains (K.eval (column76 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1079
  · exact CoefficientBounds.sound1080
  · exact CoefficientBounds.sound1081
  · exact CoefficientBounds.sound1082
  · exact CoefficientBounds.sound1083
  · exact CoefficientBounds.sound1084
  · exact CoefficientBounds.sound1085
  · exact CoefficientBounds.sound861
  · exact CoefficientBounds.sound856
  · exact CoefficientBounds.sound586
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1086
  · exact CoefficientBounds.sound1087
  · exact CoefficientBounds.sound1088
  · exact CoefficientBounds.sound1089
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound861
  · exact CoefficientBounds.sound591
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1090
  · exact CoefficientBounds.sound1091
  · exact CoefficientBounds.sound1036
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound856
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1092
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound586
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1093
  · exact CoefficientBounds.sound1094
  · exact CoefficientBounds.sound1089
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound591
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1095
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column77 : Fin 102 → K := ![CoefficientBounds.p1096,CoefficientBounds.p1097,CoefficientBounds.p1098,CoefficientBounds.p1099,CoefficientBounds.p1100,CoefficientBounds.p1101,CoefficientBounds.p1102,CoefficientBounds.p881,CoefficientBounds.p876,CoefficientBounds.p608,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1103,CoefficientBounds.p1104,CoefficientBounds.p1105,CoefficientBounds.p1106,CoefficientBounds.p0,CoefficientBounds.p881,CoefficientBounds.p613,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1107,CoefficientBounds.p1108,CoefficientBounds.p1070,CoefficientBounds.p1049,CoefficientBounds.p1109,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p1110,CoefficientBounds.p1049,CoefficientBounds.p1029,CoefficientBounds.p608,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1111,CoefficientBounds.p1112,CoefficientBounds.p1106,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p613,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1070,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1036,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p521,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes77 : Fin 102 → Dyadic := ![CoefficientBounds.b1096,CoefficientBounds.b1097,CoefficientBounds.b1098,CoefficientBounds.b1099,CoefficientBounds.b1100,CoefficientBounds.b1101,CoefficientBounds.b1102,CoefficientBounds.b881,CoefficientBounds.b876,CoefficientBounds.b608,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1103,CoefficientBounds.b1104,CoefficientBounds.b1105,CoefficientBounds.b1106,CoefficientBounds.b0,CoefficientBounds.b881,CoefficientBounds.b613,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1107,CoefficientBounds.b1108,CoefficientBounds.b1070,CoefficientBounds.b1049,CoefficientBounds.b1109,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b1110,CoefficientBounds.b1049,CoefficientBounds.b1029,CoefficientBounds.b608,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1111,CoefficientBounds.b1112,CoefficientBounds.b1106,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b613,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1070,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1036,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b521,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds77 (r : Fin 102) : (boxes77 r).Contains (K.eval (column77 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1096
  · exact CoefficientBounds.sound1097
  · exact CoefficientBounds.sound1098
  · exact CoefficientBounds.sound1099
  · exact CoefficientBounds.sound1100
  · exact CoefficientBounds.sound1101
  · exact CoefficientBounds.sound1102
  · exact CoefficientBounds.sound881
  · exact CoefficientBounds.sound876
  · exact CoefficientBounds.sound608
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1103
  · exact CoefficientBounds.sound1104
  · exact CoefficientBounds.sound1105
  · exact CoefficientBounds.sound1106
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound881
  · exact CoefficientBounds.sound613
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1107
  · exact CoefficientBounds.sound1108
  · exact CoefficientBounds.sound1070
  · exact CoefficientBounds.sound1049
  · exact CoefficientBounds.sound1109
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1110
  · exact CoefficientBounds.sound1049
  · exact CoefficientBounds.sound1029
  · exact CoefficientBounds.sound608
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1111
  · exact CoefficientBounds.sound1112
  · exact CoefficientBounds.sound1106
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound613
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1070
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1036
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound521
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column78 : Fin 102 → K := ![CoefficientBounds.p1113,CoefficientBounds.p1114,CoefficientBounds.p1115,CoefficientBounds.p1116,CoefficientBounds.p1117,CoefficientBounds.p1118,CoefficientBounds.p1119,CoefficientBounds.p901,CoefficientBounds.p896,CoefficientBounds.p630,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1120,CoefficientBounds.p1121,CoefficientBounds.p1122,CoefficientBounds.p1123,CoefficientBounds.p0,CoefficientBounds.p901,CoefficientBounds.p635,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1124,CoefficientBounds.p1118,CoefficientBounds.p1125,CoefficientBounds.p1078,CoefficientBounds.p1126,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p1127,CoefficientBounds.p1078,CoefficientBounds.p0,CoefficientBounds.p630,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1128,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1129,CoefficientBounds.p1130,CoefficientBounds.p1123,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p635,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1078,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1128,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes78 : Fin 102 → Dyadic := ![CoefficientBounds.b1113,CoefficientBounds.b1114,CoefficientBounds.b1115,CoefficientBounds.b1116,CoefficientBounds.b1117,CoefficientBounds.b1118,CoefficientBounds.b1119,CoefficientBounds.b901,CoefficientBounds.b896,CoefficientBounds.b630,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1120,CoefficientBounds.b1121,CoefficientBounds.b1122,CoefficientBounds.b1123,CoefficientBounds.b0,CoefficientBounds.b901,CoefficientBounds.b635,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1124,CoefficientBounds.b1118,CoefficientBounds.b1125,CoefficientBounds.b1078,CoefficientBounds.b1126,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b1127,CoefficientBounds.b1078,CoefficientBounds.b0,CoefficientBounds.b630,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1128,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1129,CoefficientBounds.b1130,CoefficientBounds.b1123,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b635,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1078,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1128,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds78 (r : Fin 102) : (boxes78 r).Contains (K.eval (column78 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1113
  · exact CoefficientBounds.sound1114
  · exact CoefficientBounds.sound1115
  · exact CoefficientBounds.sound1116
  · exact CoefficientBounds.sound1117
  · exact CoefficientBounds.sound1118
  · exact CoefficientBounds.sound1119
  · exact CoefficientBounds.sound901
  · exact CoefficientBounds.sound896
  · exact CoefficientBounds.sound630
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1120
  · exact CoefficientBounds.sound1121
  · exact CoefficientBounds.sound1122
  · exact CoefficientBounds.sound1123
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound901
  · exact CoefficientBounds.sound635
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1124
  · exact CoefficientBounds.sound1118
  · exact CoefficientBounds.sound1125
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound1126
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound1127
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound630
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1128
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1129
  · exact CoefficientBounds.sound1130
  · exact CoefficientBounds.sound1123
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound635
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1128
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column79 : Fin 102 → K := ![CoefficientBounds.p1131,CoefficientBounds.p1132,CoefficientBounds.p1133,CoefficientBounds.p1134,CoefficientBounds.p1135,CoefficientBounds.p1136,CoefficientBounds.p1137,CoefficientBounds.p921,CoefficientBounds.p661,CoefficientBounds.p653,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1138,CoefficientBounds.p1139,CoefficientBounds.p1140,CoefficientBounds.p1141,CoefficientBounds.p0,CoefficientBounds.p921,CoefficientBounds.p658,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1142,CoefficientBounds.p1136,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p661,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1143,CoefficientBounds.p1078,CoefficientBounds.p1036,CoefficientBounds.p1144,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1145,CoefficientBounds.p1146,CoefficientBounds.p1141,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p658,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1078,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1036,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1147,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p578,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes79 : Fin 102 → Dyadic := ![CoefficientBounds.b1131,CoefficientBounds.b1132,CoefficientBounds.b1133,CoefficientBounds.b1134,CoefficientBounds.b1135,CoefficientBounds.b1136,CoefficientBounds.b1137,CoefficientBounds.b921,CoefficientBounds.b661,CoefficientBounds.b653,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1138,CoefficientBounds.b1139,CoefficientBounds.b1140,CoefficientBounds.b1141,CoefficientBounds.b0,CoefficientBounds.b921,CoefficientBounds.b658,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1142,CoefficientBounds.b1136,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b661,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1143,CoefficientBounds.b1078,CoefficientBounds.b1036,CoefficientBounds.b1144,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1145,CoefficientBounds.b1146,CoefficientBounds.b1141,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b658,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1078,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1036,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1147,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b578,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds79 (r : Fin 102) : (boxes79 r).Contains (K.eval (column79 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1131
  · exact CoefficientBounds.sound1132
  · exact CoefficientBounds.sound1133
  · exact CoefficientBounds.sound1134
  · exact CoefficientBounds.sound1135
  · exact CoefficientBounds.sound1136
  · exact CoefficientBounds.sound1137
  · exact CoefficientBounds.sound921
  · exact CoefficientBounds.sound661
  · exact CoefficientBounds.sound653
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1138
  · exact CoefficientBounds.sound1139
  · exact CoefficientBounds.sound1140
  · exact CoefficientBounds.sound1141
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound921
  · exact CoefficientBounds.sound658
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1142
  · exact CoefficientBounds.sound1136
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound661
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1143
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound1036
  · exact CoefficientBounds.sound1144
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1145
  · exact CoefficientBounds.sound1146
  · exact CoefficientBounds.sound1141
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound658
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1078
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1036
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1147
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound578
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
