import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B019
import Coulomb8.CoefficientBounds.B020
import Coulomb8.CoefficientBounds.B021
import Coulomb8.CoefficientBounds.B022
import Coulomb8.CoefficientBounds.B023
import Coulomb8.CoefficientBounds.B024
import Coulomb8.CoefficientBounds.B025
import Coulomb8.CoefficientBounds.B026
import Coulomb8.CoefficientBounds.B027
import Coulomb8.CoefficientBounds.B028
import Coulomb8.CoefficientBounds.B029

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column104 : Fin 102 → K := ![CoefficientBounds.p1682,CoefficientBounds.p1683,CoefficientBounds.p1684,CoefficientBounds.p1685,CoefficientBounds.p1686,CoefficientBounds.p1687,CoefficientBounds.p1688,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1689,CoefficientBounds.p1690,CoefficientBounds.p1691,CoefficientBounds.p1692,CoefficientBounds.p1693,CoefficientBounds.p1453,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1694,CoefficientBounds.p1695,CoefficientBounds.p1696,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1697,CoefficientBounds.p1453,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1698,CoefficientBounds.p1699,CoefficientBounds.p1700,CoefficientBounds.p1701,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1702,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1703,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1704,CoefficientBounds.p1705,CoefficientBounds.p1706,CoefficientBounds.p1707,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1708,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes104 : Fin 102 → Dyadic := ![CoefficientBounds.b1682,CoefficientBounds.b1683,CoefficientBounds.b1684,CoefficientBounds.b1685,CoefficientBounds.b1686,CoefficientBounds.b1687,CoefficientBounds.b1688,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1689,CoefficientBounds.b1690,CoefficientBounds.b1691,CoefficientBounds.b1692,CoefficientBounds.b1693,CoefficientBounds.b1453,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1694,CoefficientBounds.b1695,CoefficientBounds.b1696,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1697,CoefficientBounds.b1453,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1698,CoefficientBounds.b1699,CoefficientBounds.b1700,CoefficientBounds.b1701,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1702,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1703,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1704,CoefficientBounds.b1705,CoefficientBounds.b1706,CoefficientBounds.b1707,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1708,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds104 (r : Fin 102) : (boxes104 r).Contains (K.eval (column104 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1682
  · exact CoefficientBounds.sound1683
  · exact CoefficientBounds.sound1684
  · exact CoefficientBounds.sound1685
  · exact CoefficientBounds.sound1686
  · exact CoefficientBounds.sound1687
  · exact CoefficientBounds.sound1688
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1689
  · exact CoefficientBounds.sound1690
  · exact CoefficientBounds.sound1691
  · exact CoefficientBounds.sound1692
  · exact CoefficientBounds.sound1693
  · exact CoefficientBounds.sound1453
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1694
  · exact CoefficientBounds.sound1695
  · exact CoefficientBounds.sound1696
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1697
  · exact CoefficientBounds.sound1453
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1698
  · exact CoefficientBounds.sound1699
  · exact CoefficientBounds.sound1700
  · exact CoefficientBounds.sound1701
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1702
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1703
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1704
  · exact CoefficientBounds.sound1705
  · exact CoefficientBounds.sound1706
  · exact CoefficientBounds.sound1707
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1708
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column105 : Fin 102 → K := ![CoefficientBounds.p1709,CoefficientBounds.p1710,CoefficientBounds.p1711,CoefficientBounds.p1712,CoefficientBounds.p1713,CoefficientBounds.p1714,CoefficientBounds.p1715,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1716,CoefficientBounds.p1717,CoefficientBounds.p1718,CoefficientBounds.p1719,CoefficientBounds.p1720,CoefficientBounds.p1721,CoefficientBounds.p1286,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1722,CoefficientBounds.p1714,CoefficientBounds.p1720,CoefficientBounds.p1723,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1482,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1724,CoefficientBounds.p1721,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1725,CoefficientBounds.p1726,CoefficientBounds.p1727,CoefficientBounds.p1728,CoefficientBounds.p1729,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1511,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1286,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes105 : Fin 102 → Dyadic := ![CoefficientBounds.b1709,CoefficientBounds.b1710,CoefficientBounds.b1711,CoefficientBounds.b1712,CoefficientBounds.b1713,CoefficientBounds.b1714,CoefficientBounds.b1715,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1716,CoefficientBounds.b1717,CoefficientBounds.b1718,CoefficientBounds.b1719,CoefficientBounds.b1720,CoefficientBounds.b1721,CoefficientBounds.b1286,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1722,CoefficientBounds.b1714,CoefficientBounds.b1720,CoefficientBounds.b1723,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1482,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1724,CoefficientBounds.b1721,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1725,CoefficientBounds.b1726,CoefficientBounds.b1727,CoefficientBounds.b1728,CoefficientBounds.b1729,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1511,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1286,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds105 (r : Fin 102) : (boxes105 r).Contains (K.eval (column105 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1709
  · exact CoefficientBounds.sound1710
  · exact CoefficientBounds.sound1711
  · exact CoefficientBounds.sound1712
  · exact CoefficientBounds.sound1713
  · exact CoefficientBounds.sound1714
  · exact CoefficientBounds.sound1715
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1716
  · exact CoefficientBounds.sound1717
  · exact CoefficientBounds.sound1718
  · exact CoefficientBounds.sound1719
  · exact CoefficientBounds.sound1720
  · exact CoefficientBounds.sound1721
  · exact CoefficientBounds.sound1286
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1722
  · exact CoefficientBounds.sound1714
  · exact CoefficientBounds.sound1720
  · exact CoefficientBounds.sound1723
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1482
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1724
  · exact CoefficientBounds.sound1721
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1725
  · exact CoefficientBounds.sound1726
  · exact CoefficientBounds.sound1727
  · exact CoefficientBounds.sound1728
  · exact CoefficientBounds.sound1729
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1511
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1286
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column106 : Fin 102 → K := ![CoefficientBounds.p1730,CoefficientBounds.p1731,CoefficientBounds.p1732,CoefficientBounds.p1733,CoefficientBounds.p1734,CoefficientBounds.p1735,CoefficientBounds.p1736,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1737,CoefficientBounds.p1738,CoefficientBounds.p1739,CoefficientBounds.p1740,CoefficientBounds.p1741,CoefficientBounds.p1524,CoefficientBounds.p1299,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1742,CoefficientBounds.p1743,CoefficientBounds.p1744,CoefficientBounds.p1745,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1746,CoefficientBounds.p1524,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1747,CoefficientBounds.p1748,CoefficientBounds.p1749,CoefficientBounds.p1750,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1728,CoefficientBounds.p1729,CoefficientBounds.p1751,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1299,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1752,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes106 : Fin 102 → Dyadic := ![CoefficientBounds.b1730,CoefficientBounds.b1731,CoefficientBounds.b1732,CoefficientBounds.b1733,CoefficientBounds.b1734,CoefficientBounds.b1735,CoefficientBounds.b1736,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1737,CoefficientBounds.b1738,CoefficientBounds.b1739,CoefficientBounds.b1740,CoefficientBounds.b1741,CoefficientBounds.b1524,CoefficientBounds.b1299,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1742,CoefficientBounds.b1743,CoefficientBounds.b1744,CoefficientBounds.b1745,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1746,CoefficientBounds.b1524,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1747,CoefficientBounds.b1748,CoefficientBounds.b1749,CoefficientBounds.b1750,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1728,CoefficientBounds.b1729,CoefficientBounds.b1751,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1299,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1752,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds106 (r : Fin 102) : (boxes106 r).Contains (K.eval (column106 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1730
  · exact CoefficientBounds.sound1731
  · exact CoefficientBounds.sound1732
  · exact CoefficientBounds.sound1733
  · exact CoefficientBounds.sound1734
  · exact CoefficientBounds.sound1735
  · exact CoefficientBounds.sound1736
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1737
  · exact CoefficientBounds.sound1738
  · exact CoefficientBounds.sound1739
  · exact CoefficientBounds.sound1740
  · exact CoefficientBounds.sound1741
  · exact CoefficientBounds.sound1524
  · exact CoefficientBounds.sound1299
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1742
  · exact CoefficientBounds.sound1743
  · exact CoefficientBounds.sound1744
  · exact CoefficientBounds.sound1745
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1746
  · exact CoefficientBounds.sound1524
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1747
  · exact CoefficientBounds.sound1748
  · exact CoefficientBounds.sound1749
  · exact CoefficientBounds.sound1750
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1728
  · exact CoefficientBounds.sound1729
  · exact CoefficientBounds.sound1751
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1299
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1752
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column107 : Fin 102 → K := ![CoefficientBounds.p1753,CoefficientBounds.p1754,CoefficientBounds.p1755,CoefficientBounds.p1756,CoefficientBounds.p1757,CoefficientBounds.p1758,CoefficientBounds.p1759,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1760,CoefficientBounds.p1761,CoefficientBounds.p1762,CoefficientBounds.p1763,CoefficientBounds.p1764,CoefficientBounds.p1548,CoefficientBounds.p1322,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1765,CoefficientBounds.p1766,CoefficientBounds.p1767,CoefficientBounds.p1768,CoefficientBounds.p1286,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1769,CoefficientBounds.p1770,CoefficientBounds.p1286,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1772,CoefficientBounds.p1773,CoefficientBounds.p1774,CoefficientBounds.p1775,CoefficientBounds.p1557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1720,CoefficientBounds.p1776,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1729,CoefficientBounds.p1322,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1777,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes107 : Fin 102 → Dyadic := ![CoefficientBounds.b1753,CoefficientBounds.b1754,CoefficientBounds.b1755,CoefficientBounds.b1756,CoefficientBounds.b1757,CoefficientBounds.b1758,CoefficientBounds.b1759,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1760,CoefficientBounds.b1761,CoefficientBounds.b1762,CoefficientBounds.b1763,CoefficientBounds.b1764,CoefficientBounds.b1548,CoefficientBounds.b1322,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1765,CoefficientBounds.b1766,CoefficientBounds.b1767,CoefficientBounds.b1768,CoefficientBounds.b1286,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1769,CoefficientBounds.b1770,CoefficientBounds.b1286,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1772,CoefficientBounds.b1773,CoefficientBounds.b1774,CoefficientBounds.b1775,CoefficientBounds.b1557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1720,CoefficientBounds.b1776,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1729,CoefficientBounds.b1322,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1777,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds107 (r : Fin 102) : (boxes107 r).Contains (K.eval (column107 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1753
  · exact CoefficientBounds.sound1754
  · exact CoefficientBounds.sound1755
  · exact CoefficientBounds.sound1756
  · exact CoefficientBounds.sound1757
  · exact CoefficientBounds.sound1758
  · exact CoefficientBounds.sound1759
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1760
  · exact CoefficientBounds.sound1761
  · exact CoefficientBounds.sound1762
  · exact CoefficientBounds.sound1763
  · exact CoefficientBounds.sound1764
  · exact CoefficientBounds.sound1548
  · exact CoefficientBounds.sound1322
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1765
  · exact CoefficientBounds.sound1766
  · exact CoefficientBounds.sound1767
  · exact CoefficientBounds.sound1768
  · exact CoefficientBounds.sound1286
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1769
  · exact CoefficientBounds.sound1770
  · exact CoefficientBounds.sound1286
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1772
  · exact CoefficientBounds.sound1773
  · exact CoefficientBounds.sound1774
  · exact CoefficientBounds.sound1775
  · exact CoefficientBounds.sound1557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1720
  · exact CoefficientBounds.sound1776
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1729
  · exact CoefficientBounds.sound1322
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1777
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column108 : Fin 102 → K := ![CoefficientBounds.p1778,CoefficientBounds.p1779,CoefficientBounds.p1780,CoefficientBounds.p1781,CoefficientBounds.p1782,CoefficientBounds.p1783,CoefficientBounds.p1784,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1785,CoefficientBounds.p1786,CoefficientBounds.p1787,CoefficientBounds.p1788,CoefficientBounds.p1789,CoefficientBounds.p1573,CoefficientBounds.p1343,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1790,CoefficientBounds.p1783,CoefficientBounds.p1791,CoefficientBounds.p1792,CoefficientBounds.p1777,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1793,CoefficientBounds.p1794,CoefficientBounds.p1729,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p1795,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1796,CoefficientBounds.p1797,CoefficientBounds.p1798,CoefficientBounds.p1799,CoefficientBounds.p1583,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1800,CoefficientBounds.p1729,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1801,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1802,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes108 : Fin 102 → Dyadic := ![CoefficientBounds.b1778,CoefficientBounds.b1779,CoefficientBounds.b1780,CoefficientBounds.b1781,CoefficientBounds.b1782,CoefficientBounds.b1783,CoefficientBounds.b1784,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1785,CoefficientBounds.b1786,CoefficientBounds.b1787,CoefficientBounds.b1788,CoefficientBounds.b1789,CoefficientBounds.b1573,CoefficientBounds.b1343,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1790,CoefficientBounds.b1783,CoefficientBounds.b1791,CoefficientBounds.b1792,CoefficientBounds.b1777,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1793,CoefficientBounds.b1794,CoefficientBounds.b1729,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b1795,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1796,CoefficientBounds.b1797,CoefficientBounds.b1798,CoefficientBounds.b1799,CoefficientBounds.b1583,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1800,CoefficientBounds.b1729,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1801,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1802,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds108 (r : Fin 102) : (boxes108 r).Contains (K.eval (column108 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1778
  · exact CoefficientBounds.sound1779
  · exact CoefficientBounds.sound1780
  · exact CoefficientBounds.sound1781
  · exact CoefficientBounds.sound1782
  · exact CoefficientBounds.sound1783
  · exact CoefficientBounds.sound1784
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1785
  · exact CoefficientBounds.sound1786
  · exact CoefficientBounds.sound1787
  · exact CoefficientBounds.sound1788
  · exact CoefficientBounds.sound1789
  · exact CoefficientBounds.sound1573
  · exact CoefficientBounds.sound1343
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1790
  · exact CoefficientBounds.sound1783
  · exact CoefficientBounds.sound1791
  · exact CoefficientBounds.sound1792
  · exact CoefficientBounds.sound1777
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1793
  · exact CoefficientBounds.sound1794
  · exact CoefficientBounds.sound1729
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1795
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1796
  · exact CoefficientBounds.sound1797
  · exact CoefficientBounds.sound1798
  · exact CoefficientBounds.sound1799
  · exact CoefficientBounds.sound1583
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1800
  · exact CoefficientBounds.sound1729
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1801
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1802
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column109 : Fin 102 → K := ![CoefficientBounds.p1803,CoefficientBounds.p1804,CoefficientBounds.p1805,CoefficientBounds.p1806,CoefficientBounds.p1807,CoefficientBounds.p1808,CoefficientBounds.p1809,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1810,CoefficientBounds.p1811,CoefficientBounds.p1812,CoefficientBounds.p1813,CoefficientBounds.p1814,CoefficientBounds.p1597,CoefficientBounds.p1365,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1815,CoefficientBounds.p1808,CoefficientBounds.p1814,CoefficientBounds.p1600,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1816,CoefficientBounds.p1817,CoefficientBounds.p1777,CoefficientBounds.p1512,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1818,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1819,CoefficientBounds.p1820,CoefficientBounds.p1821,CoefficientBounds.p1822,CoefficientBounds.p1606,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1607,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1728,CoefficientBounds.p1823,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1777,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1824,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes109 : Fin 102 → Dyadic := ![CoefficientBounds.b1803,CoefficientBounds.b1804,CoefficientBounds.b1805,CoefficientBounds.b1806,CoefficientBounds.b1807,CoefficientBounds.b1808,CoefficientBounds.b1809,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1810,CoefficientBounds.b1811,CoefficientBounds.b1812,CoefficientBounds.b1813,CoefficientBounds.b1814,CoefficientBounds.b1597,CoefficientBounds.b1365,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1815,CoefficientBounds.b1808,CoefficientBounds.b1814,CoefficientBounds.b1600,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1816,CoefficientBounds.b1817,CoefficientBounds.b1777,CoefficientBounds.b1512,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1818,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1819,CoefficientBounds.b1820,CoefficientBounds.b1821,CoefficientBounds.b1822,CoefficientBounds.b1606,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1607,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1728,CoefficientBounds.b1823,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1777,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1824,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds109 (r : Fin 102) : (boxes109 r).Contains (K.eval (column109 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1803
  · exact CoefficientBounds.sound1804
  · exact CoefficientBounds.sound1805
  · exact CoefficientBounds.sound1806
  · exact CoefficientBounds.sound1807
  · exact CoefficientBounds.sound1808
  · exact CoefficientBounds.sound1809
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1810
  · exact CoefficientBounds.sound1811
  · exact CoefficientBounds.sound1812
  · exact CoefficientBounds.sound1813
  · exact CoefficientBounds.sound1814
  · exact CoefficientBounds.sound1597
  · exact CoefficientBounds.sound1365
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1815
  · exact CoefficientBounds.sound1808
  · exact CoefficientBounds.sound1814
  · exact CoefficientBounds.sound1600
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1816
  · exact CoefficientBounds.sound1817
  · exact CoefficientBounds.sound1777
  · exact CoefficientBounds.sound1512
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1818
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1819
  · exact CoefficientBounds.sound1820
  · exact CoefficientBounds.sound1821
  · exact CoefficientBounds.sound1822
  · exact CoefficientBounds.sound1606
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1607
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1728
  · exact CoefficientBounds.sound1823
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1777
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1824
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column110 : Fin 102 → K := ![CoefficientBounds.p1825,CoefficientBounds.p1826,CoefficientBounds.p1827,CoefficientBounds.p1828,CoefficientBounds.p1829,CoefficientBounds.p1830,CoefficientBounds.p1831,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1832,CoefficientBounds.p1833,CoefficientBounds.p1834,CoefficientBounds.p1835,CoefficientBounds.p1836,CoefficientBounds.p1621,CoefficientBounds.p1385,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1837,CoefficientBounds.p1830,CoefficientBounds.p1836,CoefficientBounds.p1624,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1838,CoefficientBounds.p1621,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1633,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1839,CoefficientBounds.p1840,CoefficientBounds.p1841,CoefficientBounds.p1842,CoefficientBounds.p1843,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1844,CoefficientBounds.p0,CoefficientBounds.p1631,CoefficientBounds.p1632,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1385,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes110 : Fin 102 → Dyadic := ![CoefficientBounds.b1825,CoefficientBounds.b1826,CoefficientBounds.b1827,CoefficientBounds.b1828,CoefficientBounds.b1829,CoefficientBounds.b1830,CoefficientBounds.b1831,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1832,CoefficientBounds.b1833,CoefficientBounds.b1834,CoefficientBounds.b1835,CoefficientBounds.b1836,CoefficientBounds.b1621,CoefficientBounds.b1385,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1837,CoefficientBounds.b1830,CoefficientBounds.b1836,CoefficientBounds.b1624,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1838,CoefficientBounds.b1621,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1633,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1839,CoefficientBounds.b1840,CoefficientBounds.b1841,CoefficientBounds.b1842,CoefficientBounds.b1843,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1844,CoefficientBounds.b0,CoefficientBounds.b1631,CoefficientBounds.b1632,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1385,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds110 (r : Fin 102) : (boxes110 r).Contains (K.eval (column110 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1825
  · exact CoefficientBounds.sound1826
  · exact CoefficientBounds.sound1827
  · exact CoefficientBounds.sound1828
  · exact CoefficientBounds.sound1829
  · exact CoefficientBounds.sound1830
  · exact CoefficientBounds.sound1831
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1832
  · exact CoefficientBounds.sound1833
  · exact CoefficientBounds.sound1834
  · exact CoefficientBounds.sound1835
  · exact CoefficientBounds.sound1836
  · exact CoefficientBounds.sound1621
  · exact CoefficientBounds.sound1385
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1837
  · exact CoefficientBounds.sound1830
  · exact CoefficientBounds.sound1836
  · exact CoefficientBounds.sound1624
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1838
  · exact CoefficientBounds.sound1621
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1633
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1839
  · exact CoefficientBounds.sound1840
  · exact CoefficientBounds.sound1841
  · exact CoefficientBounds.sound1842
  · exact CoefficientBounds.sound1843
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1844
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1631
  · exact CoefficientBounds.sound1632
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1385
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column111 : Fin 102 → K := ![CoefficientBounds.p1845,CoefficientBounds.p1846,CoefficientBounds.p1847,CoefficientBounds.p1848,CoefficientBounds.p1849,CoefficientBounds.p1850,CoefficientBounds.p1851,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1852,CoefficientBounds.p1853,CoefficientBounds.p1854,CoefficientBounds.p1855,CoefficientBounds.p1856,CoefficientBounds.p1645,CoefficientBounds.p1406,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1857,CoefficientBounds.p1850,CoefficientBounds.p1856,CoefficientBounds.p1648,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1858,CoefficientBounds.p1645,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1656,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1859,CoefficientBounds.p1860,CoefficientBounds.p1861,CoefficientBounds.p1862,CoefficientBounds.p1863,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1864,CoefficientBounds.p1285,CoefficientBounds.p1865,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1406,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1866,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes111 : Fin 102 → Dyadic := ![CoefficientBounds.b1845,CoefficientBounds.b1846,CoefficientBounds.b1847,CoefficientBounds.b1848,CoefficientBounds.b1849,CoefficientBounds.b1850,CoefficientBounds.b1851,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1852,CoefficientBounds.b1853,CoefficientBounds.b1854,CoefficientBounds.b1855,CoefficientBounds.b1856,CoefficientBounds.b1645,CoefficientBounds.b1406,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1857,CoefficientBounds.b1850,CoefficientBounds.b1856,CoefficientBounds.b1648,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1858,CoefficientBounds.b1645,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1656,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1859,CoefficientBounds.b1860,CoefficientBounds.b1861,CoefficientBounds.b1862,CoefficientBounds.b1863,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1864,CoefficientBounds.b1285,CoefficientBounds.b1865,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1406,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1866,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds111 (r : Fin 102) : (boxes111 r).Contains (K.eval (column111 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1845
  · exact CoefficientBounds.sound1846
  · exact CoefficientBounds.sound1847
  · exact CoefficientBounds.sound1848
  · exact CoefficientBounds.sound1849
  · exact CoefficientBounds.sound1850
  · exact CoefficientBounds.sound1851
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1852
  · exact CoefficientBounds.sound1853
  · exact CoefficientBounds.sound1854
  · exact CoefficientBounds.sound1855
  · exact CoefficientBounds.sound1856
  · exact CoefficientBounds.sound1645
  · exact CoefficientBounds.sound1406
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1857
  · exact CoefficientBounds.sound1850
  · exact CoefficientBounds.sound1856
  · exact CoefficientBounds.sound1648
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1858
  · exact CoefficientBounds.sound1645
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1656
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1859
  · exact CoefficientBounds.sound1860
  · exact CoefficientBounds.sound1861
  · exact CoefficientBounds.sound1862
  · exact CoefficientBounds.sound1863
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1864
  · exact CoefficientBounds.sound1285
  · exact CoefficientBounds.sound1865
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1406
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1866
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
