import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B019
import Coulomb8.CoefficientBounds.B020
import Coulomb8.CoefficientBounds.B021
import Coulomb8.CoefficientBounds.B022
import Coulomb8.CoefficientBounds.B023
import Coulomb8.CoefficientBounds.B024
import Coulomb8.CoefficientBounds.B025
import Coulomb8.CoefficientBounds.B026
import Coulomb8.CoefficientBounds.B027
import Coulomb8.CoefficientBounds.B028
import Coulomb8.CoefficientBounds.B029
import Coulomb8.CoefficientBounds.B030
import Coulomb8.CoefficientBounds.B031

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column112 : Fin 102 → K := ![CoefficientBounds.p1867,CoefficientBounds.p1868,CoefficientBounds.p1869,CoefficientBounds.p1870,CoefficientBounds.p1871,CoefficientBounds.p1872,CoefficientBounds.p1873,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1874,CoefficientBounds.p1875,CoefficientBounds.p1876,CoefficientBounds.p1877,CoefficientBounds.p1878,CoefficientBounds.p1669,CoefficientBounds.p1427,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1879,CoefficientBounds.p1872,CoefficientBounds.p1878,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1880,CoefficientBounds.p1669,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1881,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1882,CoefficientBounds.p1883,CoefficientBounds.p1884,CoefficientBounds.p1885,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1886,CoefficientBounds.p1864,CoefficientBounds.p1887,CoefficientBounds.p1888,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1889,CoefficientBounds.p1427,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1890,CoefficientBounds.p1891,CoefficientBounds.p1888,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes112 : Fin 102 → Dyadic := ![CoefficientBounds.b1867,CoefficientBounds.b1868,CoefficientBounds.b1869,CoefficientBounds.b1870,CoefficientBounds.b1871,CoefficientBounds.b1872,CoefficientBounds.b1873,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1874,CoefficientBounds.b1875,CoefficientBounds.b1876,CoefficientBounds.b1877,CoefficientBounds.b1878,CoefficientBounds.b1669,CoefficientBounds.b1427,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1879,CoefficientBounds.b1872,CoefficientBounds.b1878,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1880,CoefficientBounds.b1669,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1881,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1882,CoefficientBounds.b1883,CoefficientBounds.b1884,CoefficientBounds.b1885,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1886,CoefficientBounds.b1864,CoefficientBounds.b1887,CoefficientBounds.b1888,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1889,CoefficientBounds.b1427,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1890,CoefficientBounds.b1891,CoefficientBounds.b1888,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds112 (r : Fin 102) : (boxes112 r).Contains (K.eval (column112 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1867
  · exact CoefficientBounds.sound1868
  · exact CoefficientBounds.sound1869
  · exact CoefficientBounds.sound1870
  · exact CoefficientBounds.sound1871
  · exact CoefficientBounds.sound1872
  · exact CoefficientBounds.sound1873
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1874
  · exact CoefficientBounds.sound1875
  · exact CoefficientBounds.sound1876
  · exact CoefficientBounds.sound1877
  · exact CoefficientBounds.sound1878
  · exact CoefficientBounds.sound1669
  · exact CoefficientBounds.sound1427
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1879
  · exact CoefficientBounds.sound1872
  · exact CoefficientBounds.sound1878
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1880
  · exact CoefficientBounds.sound1669
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1881
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1882
  · exact CoefficientBounds.sound1883
  · exact CoefficientBounds.sound1884
  · exact CoefficientBounds.sound1885
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1886
  · exact CoefficientBounds.sound1864
  · exact CoefficientBounds.sound1887
  · exact CoefficientBounds.sound1888
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1889
  · exact CoefficientBounds.sound1427
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1890
  · exact CoefficientBounds.sound1891
  · exact CoefficientBounds.sound1888
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column113 : Fin 102 → K := ![CoefficientBounds.p1892,CoefficientBounds.p1893,CoefficientBounds.p1894,CoefficientBounds.p1895,CoefficientBounds.p1896,CoefficientBounds.p1897,CoefficientBounds.p1898,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1899,CoefficientBounds.p1900,CoefficientBounds.p1901,CoefficientBounds.p1902,CoefficientBounds.p1903,CoefficientBounds.p1693,CoefficientBounds.p1453,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1904,CoefficientBounds.p1897,CoefficientBounds.p1903,CoefficientBounds.p1696,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1905,CoefficientBounds.p1693,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1703,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1906,CoefficientBounds.p1907,CoefficientBounds.p1908,CoefficientBounds.p1909,CoefficientBounds.p1701,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1702,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1453,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1910,CoefficientBounds.p1911,CoefficientBounds.p1912,CoefficientBounds.p1913,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1914,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes113 : Fin 102 → Dyadic := ![CoefficientBounds.b1892,CoefficientBounds.b1893,CoefficientBounds.b1894,CoefficientBounds.b1895,CoefficientBounds.b1896,CoefficientBounds.b1897,CoefficientBounds.b1898,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1899,CoefficientBounds.b1900,CoefficientBounds.b1901,CoefficientBounds.b1902,CoefficientBounds.b1903,CoefficientBounds.b1693,CoefficientBounds.b1453,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1904,CoefficientBounds.b1897,CoefficientBounds.b1903,CoefficientBounds.b1696,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1905,CoefficientBounds.b1693,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1703,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1906,CoefficientBounds.b1907,CoefficientBounds.b1908,CoefficientBounds.b1909,CoefficientBounds.b1701,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1702,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1453,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1910,CoefficientBounds.b1911,CoefficientBounds.b1912,CoefficientBounds.b1913,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1914,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds113 (r : Fin 102) : (boxes113 r).Contains (K.eval (column113 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1892
  · exact CoefficientBounds.sound1893
  · exact CoefficientBounds.sound1894
  · exact CoefficientBounds.sound1895
  · exact CoefficientBounds.sound1896
  · exact CoefficientBounds.sound1897
  · exact CoefficientBounds.sound1898
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1899
  · exact CoefficientBounds.sound1900
  · exact CoefficientBounds.sound1901
  · exact CoefficientBounds.sound1902
  · exact CoefficientBounds.sound1903
  · exact CoefficientBounds.sound1693
  · exact CoefficientBounds.sound1453
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1904
  · exact CoefficientBounds.sound1897
  · exact CoefficientBounds.sound1903
  · exact CoefficientBounds.sound1696
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1905
  · exact CoefficientBounds.sound1693
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1703
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1906
  · exact CoefficientBounds.sound1907
  · exact CoefficientBounds.sound1908
  · exact CoefficientBounds.sound1909
  · exact CoefficientBounds.sound1701
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1702
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1453
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1910
  · exact CoefficientBounds.sound1911
  · exact CoefficientBounds.sound1912
  · exact CoefficientBounds.sound1913
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1914
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column114 : Fin 102 → K := ![CoefficientBounds.p1915,CoefficientBounds.p1916,CoefficientBounds.p1917,CoefficientBounds.p1918,CoefficientBounds.p1919,CoefficientBounds.p1920,CoefficientBounds.p1921,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1922,CoefficientBounds.p1923,CoefficientBounds.p1924,CoefficientBounds.p1925,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1926,CoefficientBounds.p1927,CoefficientBounds.p1928,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1929,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1930,CoefficientBounds.p1931,CoefficientBounds.p1925,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1750,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1932,CoefficientBounds.p1535,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes114 : Fin 102 → Dyadic := ![CoefficientBounds.b1915,CoefficientBounds.b1916,CoefficientBounds.b1917,CoefficientBounds.b1918,CoefficientBounds.b1919,CoefficientBounds.b1920,CoefficientBounds.b1921,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1922,CoefficientBounds.b1923,CoefficientBounds.b1924,CoefficientBounds.b1925,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1926,CoefficientBounds.b1927,CoefficientBounds.b1928,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1929,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1930,CoefficientBounds.b1931,CoefficientBounds.b1925,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1750,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1932,CoefficientBounds.b1535,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds114 (r : Fin 102) : (boxes114 r).Contains (K.eval (column114 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1915
  · exact CoefficientBounds.sound1916
  · exact CoefficientBounds.sound1917
  · exact CoefficientBounds.sound1918
  · exact CoefficientBounds.sound1919
  · exact CoefficientBounds.sound1920
  · exact CoefficientBounds.sound1921
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1922
  · exact CoefficientBounds.sound1923
  · exact CoefficientBounds.sound1924
  · exact CoefficientBounds.sound1925
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1926
  · exact CoefficientBounds.sound1927
  · exact CoefficientBounds.sound1928
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1929
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1930
  · exact CoefficientBounds.sound1931
  · exact CoefficientBounds.sound1925
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1750
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1932
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column115 : Fin 102 → K := ![CoefficientBounds.p1933,CoefficientBounds.p1934,CoefficientBounds.p1935,CoefficientBounds.p1936,CoefficientBounds.p1937,CoefficientBounds.p1938,CoefficientBounds.p1939,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1940,CoefficientBounds.p1941,CoefficientBounds.p1942,CoefficientBounds.p1943,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1944,CoefficientBounds.p1945,CoefficientBounds.p1946,CoefficientBounds.p1947,CoefficientBounds.p1299,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1948,CoefficientBounds.p1751,CoefficientBounds.p1299,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1949,CoefficientBounds.p1950,CoefficientBounds.p1943,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1775,CoefficientBounds.p1951,CoefficientBounds.p1952,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1953,CoefficientBounds.p1954,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1535,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes115 : Fin 102 → Dyadic := ![CoefficientBounds.b1933,CoefficientBounds.b1934,CoefficientBounds.b1935,CoefficientBounds.b1936,CoefficientBounds.b1937,CoefficientBounds.b1938,CoefficientBounds.b1939,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1940,CoefficientBounds.b1941,CoefficientBounds.b1942,CoefficientBounds.b1943,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1944,CoefficientBounds.b1945,CoefficientBounds.b1946,CoefficientBounds.b1947,CoefficientBounds.b1299,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1948,CoefficientBounds.b1751,CoefficientBounds.b1299,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1949,CoefficientBounds.b1950,CoefficientBounds.b1943,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1775,CoefficientBounds.b1951,CoefficientBounds.b1952,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1953,CoefficientBounds.b1954,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1535,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds115 (r : Fin 102) : (boxes115 r).Contains (K.eval (column115 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1933
  · exact CoefficientBounds.sound1934
  · exact CoefficientBounds.sound1935
  · exact CoefficientBounds.sound1936
  · exact CoefficientBounds.sound1937
  · exact CoefficientBounds.sound1938
  · exact CoefficientBounds.sound1939
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1940
  · exact CoefficientBounds.sound1941
  · exact CoefficientBounds.sound1942
  · exact CoefficientBounds.sound1943
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1944
  · exact CoefficientBounds.sound1945
  · exact CoefficientBounds.sound1946
  · exact CoefficientBounds.sound1947
  · exact CoefficientBounds.sound1299
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1948
  · exact CoefficientBounds.sound1751
  · exact CoefficientBounds.sound1299
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1949
  · exact CoefficientBounds.sound1950
  · exact CoefficientBounds.sound1943
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1775
  · exact CoefficientBounds.sound1951
  · exact CoefficientBounds.sound1952
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1953
  · exact CoefficientBounds.sound1954
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column116 : Fin 102 → K := ![CoefficientBounds.p1955,CoefficientBounds.p1956,CoefficientBounds.p1957,CoefficientBounds.p1958,CoefficientBounds.p1959,CoefficientBounds.p1960,CoefficientBounds.p1961,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1962,CoefficientBounds.p1963,CoefficientBounds.p1964,CoefficientBounds.p1965,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1966,CoefficientBounds.p1967,CoefficientBounds.p1968,CoefficientBounds.p1969,CoefficientBounds.p1928,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1970,CoefficientBounds.p1750,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1971,CoefficientBounds.p1535,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1972,CoefficientBounds.p1973,CoefficientBounds.p1965,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1799,CoefficientBounds.p1583,CoefficientBounds.p1750,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1974,CoefficientBounds.p1585,CoefficientBounds.p1971,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes116 : Fin 102 → Dyadic := ![CoefficientBounds.b1955,CoefficientBounds.b1956,CoefficientBounds.b1957,CoefficientBounds.b1958,CoefficientBounds.b1959,CoefficientBounds.b1960,CoefficientBounds.b1961,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1962,CoefficientBounds.b1963,CoefficientBounds.b1964,CoefficientBounds.b1965,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1966,CoefficientBounds.b1967,CoefficientBounds.b1968,CoefficientBounds.b1969,CoefficientBounds.b1928,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1970,CoefficientBounds.b1750,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1971,CoefficientBounds.b1535,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1972,CoefficientBounds.b1973,CoefficientBounds.b1965,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1799,CoefficientBounds.b1583,CoefficientBounds.b1750,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1974,CoefficientBounds.b1585,CoefficientBounds.b1971,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds116 (r : Fin 102) : (boxes116 r).Contains (K.eval (column116 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1955
  · exact CoefficientBounds.sound1956
  · exact CoefficientBounds.sound1957
  · exact CoefficientBounds.sound1958
  · exact CoefficientBounds.sound1959
  · exact CoefficientBounds.sound1960
  · exact CoefficientBounds.sound1961
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1962
  · exact CoefficientBounds.sound1963
  · exact CoefficientBounds.sound1964
  · exact CoefficientBounds.sound1965
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1966
  · exact CoefficientBounds.sound1967
  · exact CoefficientBounds.sound1968
  · exact CoefficientBounds.sound1969
  · exact CoefficientBounds.sound1928
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1970
  · exact CoefficientBounds.sound1750
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1971
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1972
  · exact CoefficientBounds.sound1973
  · exact CoefficientBounds.sound1965
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1799
  · exact CoefficientBounds.sound1583
  · exact CoefficientBounds.sound1750
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1974
  · exact CoefficientBounds.sound1585
  · exact CoefficientBounds.sound1971
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column117 : Fin 102 → K := ![CoefficientBounds.p1975,CoefficientBounds.p1976,CoefficientBounds.p1977,CoefficientBounds.p1978,CoefficientBounds.p1979,CoefficientBounds.p1980,CoefficientBounds.p1981,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1982,CoefficientBounds.p1983,CoefficientBounds.p1984,CoefficientBounds.p1985,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1986,CoefficientBounds.p1987,CoefficientBounds.p1988,CoefficientBounds.p1989,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1990,CoefficientBounds.p1750,CoefficientBounds.p1928,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1991,CoefficientBounds.p1992,CoefficientBounds.p1985,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1822,CoefficientBounds.p1606,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1750,CoefficientBounds.p1532,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1993,CoefficientBounds.p1989,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1928,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1994,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes117 : Fin 102 → Dyadic := ![CoefficientBounds.b1975,CoefficientBounds.b1976,CoefficientBounds.b1977,CoefficientBounds.b1978,CoefficientBounds.b1979,CoefficientBounds.b1980,CoefficientBounds.b1981,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1982,CoefficientBounds.b1983,CoefficientBounds.b1984,CoefficientBounds.b1985,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1986,CoefficientBounds.b1987,CoefficientBounds.b1988,CoefficientBounds.b1989,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1990,CoefficientBounds.b1750,CoefficientBounds.b1928,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1991,CoefficientBounds.b1992,CoefficientBounds.b1985,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1822,CoefficientBounds.b1606,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1750,CoefficientBounds.b1532,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1993,CoefficientBounds.b1989,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1928,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1994,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds117 (r : Fin 102) : (boxes117 r).Contains (K.eval (column117 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1975
  · exact CoefficientBounds.sound1976
  · exact CoefficientBounds.sound1977
  · exact CoefficientBounds.sound1978
  · exact CoefficientBounds.sound1979
  · exact CoefficientBounds.sound1980
  · exact CoefficientBounds.sound1981
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1982
  · exact CoefficientBounds.sound1983
  · exact CoefficientBounds.sound1984
  · exact CoefficientBounds.sound1985
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1986
  · exact CoefficientBounds.sound1987
  · exact CoefficientBounds.sound1988
  · exact CoefficientBounds.sound1989
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1990
  · exact CoefficientBounds.sound1750
  · exact CoefficientBounds.sound1928
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1991
  · exact CoefficientBounds.sound1992
  · exact CoefficientBounds.sound1985
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1822
  · exact CoefficientBounds.sound1606
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1750
  · exact CoefficientBounds.sound1532
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1993
  · exact CoefficientBounds.sound1989
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1928
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1994
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column118 : Fin 102 → K := ![CoefficientBounds.p1995,CoefficientBounds.p1996,CoefficientBounds.p1997,CoefficientBounds.p1998,CoefficientBounds.p1999,CoefficientBounds.p2000,CoefficientBounds.p2001,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2002,CoefficientBounds.p2003,CoefficientBounds.p2004,CoefficientBounds.p2005,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2006,CoefficientBounds.p2007,CoefficientBounds.p2008,CoefficientBounds.p1633,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2009,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2010,CoefficientBounds.p2011,CoefficientBounds.p2012,CoefficientBounds.p2013,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2014,CoefficientBounds.p1843,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2015,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2016,CoefficientBounds.p1633,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes118 : Fin 102 → Dyadic := ![CoefficientBounds.b1995,CoefficientBounds.b1996,CoefficientBounds.b1997,CoefficientBounds.b1998,CoefficientBounds.b1999,CoefficientBounds.b2000,CoefficientBounds.b2001,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2002,CoefficientBounds.b2003,CoefficientBounds.b2004,CoefficientBounds.b2005,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2006,CoefficientBounds.b2007,CoefficientBounds.b2008,CoefficientBounds.b1633,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2009,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2010,CoefficientBounds.b2011,CoefficientBounds.b2012,CoefficientBounds.b2013,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2014,CoefficientBounds.b1843,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2015,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2016,CoefficientBounds.b1633,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds118 (r : Fin 102) : (boxes118 r).Contains (K.eval (column118 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound1995
  · exact CoefficientBounds.sound1996
  · exact CoefficientBounds.sound1997
  · exact CoefficientBounds.sound1998
  · exact CoefficientBounds.sound1999
  · exact CoefficientBounds.sound2000
  · exact CoefficientBounds.sound2001
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2002
  · exact CoefficientBounds.sound2003
  · exact CoefficientBounds.sound2004
  · exact CoefficientBounds.sound2005
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2006
  · exact CoefficientBounds.sound2007
  · exact CoefficientBounds.sound2008
  · exact CoefficientBounds.sound1633
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2009
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2010
  · exact CoefficientBounds.sound2011
  · exact CoefficientBounds.sound2012
  · exact CoefficientBounds.sound2013
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2014
  · exact CoefficientBounds.sound1843
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2015
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2016
  · exact CoefficientBounds.sound1633
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column119 : Fin 102 → K := ![CoefficientBounds.p2017,CoefficientBounds.p2018,CoefficientBounds.p2019,CoefficientBounds.p2020,CoefficientBounds.p2021,CoefficientBounds.p2022,CoefficientBounds.p2023,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2024,CoefficientBounds.p2025,CoefficientBounds.p2026,CoefficientBounds.p2027,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2028,CoefficientBounds.p2029,CoefficientBounds.p2030,CoefficientBounds.p1656,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2031,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2032,CoefficientBounds.p2033,CoefficientBounds.p2034,CoefficientBounds.p1928,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2035,CoefficientBounds.p2036,CoefficientBounds.p1535,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2037,CoefficientBounds.p1656,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes119 : Fin 102 → Dyadic := ![CoefficientBounds.b2017,CoefficientBounds.b2018,CoefficientBounds.b2019,CoefficientBounds.b2020,CoefficientBounds.b2021,CoefficientBounds.b2022,CoefficientBounds.b2023,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2024,CoefficientBounds.b2025,CoefficientBounds.b2026,CoefficientBounds.b2027,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2028,CoefficientBounds.b2029,CoefficientBounds.b2030,CoefficientBounds.b1656,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2031,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2032,CoefficientBounds.b2033,CoefficientBounds.b2034,CoefficientBounds.b1928,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2035,CoefficientBounds.b2036,CoefficientBounds.b1535,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2037,CoefficientBounds.b1656,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds119 (r : Fin 102) : (boxes119 r).Contains (K.eval (column119 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2017
  · exact CoefficientBounds.sound2018
  · exact CoefficientBounds.sound2019
  · exact CoefficientBounds.sound2020
  · exact CoefficientBounds.sound2021
  · exact CoefficientBounds.sound2022
  · exact CoefficientBounds.sound2023
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2024
  · exact CoefficientBounds.sound2025
  · exact CoefficientBounds.sound2026
  · exact CoefficientBounds.sound2027
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2028
  · exact CoefficientBounds.sound2029
  · exact CoefficientBounds.sound2030
  · exact CoefficientBounds.sound1656
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2031
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2032
  · exact CoefficientBounds.sound2033
  · exact CoefficientBounds.sound2034
  · exact CoefficientBounds.sound1928
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2035
  · exact CoefficientBounds.sound2036
  · exact CoefficientBounds.sound1535
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2037
  · exact CoefficientBounds.sound1656
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
