import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B019
import Coulomb8.CoefficientBounds.B020
import Coulomb8.CoefficientBounds.B021
import Coulomb8.CoefficientBounds.B022
import Coulomb8.CoefficientBounds.B023
import Coulomb8.CoefficientBounds.B024
import Coulomb8.CoefficientBounds.B025
import Coulomb8.CoefficientBounds.B026
import Coulomb8.CoefficientBounds.B027
import Coulomb8.CoefficientBounds.B028
import Coulomb8.CoefficientBounds.B029
import Coulomb8.CoefficientBounds.B030
import Coulomb8.CoefficientBounds.B031
import Coulomb8.CoefficientBounds.B032
import Coulomb8.CoefficientBounds.B033
import Coulomb8.CoefficientBounds.B034

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column120 : Fin 102 → K := ![CoefficientBounds.p2038,CoefficientBounds.p2039,CoefficientBounds.p2040,CoefficientBounds.p2041,CoefficientBounds.p2042,CoefficientBounds.p2043,CoefficientBounds.p2044,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2045,CoefficientBounds.p2046,CoefficientBounds.p2047,CoefficientBounds.p2048,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2049,CoefficientBounds.p2050,CoefficientBounds.p2051,CoefficientBounds.p1881,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2052,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2053,CoefficientBounds.p2054,CoefficientBounds.p2048,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2055,CoefficientBounds.p2056,CoefficientBounds.p1971,CoefficientBounds.p2057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2058,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2059,CoefficientBounds.p2060,CoefficientBounds.p2057,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes120 : Fin 102 → Dyadic := ![CoefficientBounds.b2038,CoefficientBounds.b2039,CoefficientBounds.b2040,CoefficientBounds.b2041,CoefficientBounds.b2042,CoefficientBounds.b2043,CoefficientBounds.b2044,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2045,CoefficientBounds.b2046,CoefficientBounds.b2047,CoefficientBounds.b2048,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2049,CoefficientBounds.b2050,CoefficientBounds.b2051,CoefficientBounds.b1881,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2052,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2053,CoefficientBounds.b2054,CoefficientBounds.b2048,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2055,CoefficientBounds.b2056,CoefficientBounds.b1971,CoefficientBounds.b2057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2058,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2059,CoefficientBounds.b2060,CoefficientBounds.b2057,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds120 (r : Fin 102) : (boxes120 r).Contains (K.eval (column120 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2038
  · exact CoefficientBounds.sound2039
  · exact CoefficientBounds.sound2040
  · exact CoefficientBounds.sound2041
  · exact CoefficientBounds.sound2042
  · exact CoefficientBounds.sound2043
  · exact CoefficientBounds.sound2044
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2045
  · exact CoefficientBounds.sound2046
  · exact CoefficientBounds.sound2047
  · exact CoefficientBounds.sound2048
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2049
  · exact CoefficientBounds.sound2050
  · exact CoefficientBounds.sound2051
  · exact CoefficientBounds.sound1881
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2052
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2053
  · exact CoefficientBounds.sound2054
  · exact CoefficientBounds.sound2048
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2055
  · exact CoefficientBounds.sound2056
  · exact CoefficientBounds.sound1971
  · exact CoefficientBounds.sound2057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2058
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2059
  · exact CoefficientBounds.sound2060
  · exact CoefficientBounds.sound2057
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column121 : Fin 102 → K := ![CoefficientBounds.p2061,CoefficientBounds.p2062,CoefficientBounds.p2063,CoefficientBounds.p2064,CoefficientBounds.p2065,CoefficientBounds.p2066,CoefficientBounds.p2067,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2068,CoefficientBounds.p2069,CoefficientBounds.p2070,CoefficientBounds.p2071,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2072,CoefficientBounds.p2073,CoefficientBounds.p2074,CoefficientBounds.p1703,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2075,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2076,CoefficientBounds.p2077,CoefficientBounds.p2071,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1909,CoefficientBounds.p1701,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2078,CoefficientBounds.p2079,CoefficientBounds.p2080,CoefficientBounds.p2081,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2082,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2083,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes121 : Fin 102 → Dyadic := ![CoefficientBounds.b2061,CoefficientBounds.b2062,CoefficientBounds.b2063,CoefficientBounds.b2064,CoefficientBounds.b2065,CoefficientBounds.b2066,CoefficientBounds.b2067,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2068,CoefficientBounds.b2069,CoefficientBounds.b2070,CoefficientBounds.b2071,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2072,CoefficientBounds.b2073,CoefficientBounds.b2074,CoefficientBounds.b1703,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2075,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2076,CoefficientBounds.b2077,CoefficientBounds.b2071,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1909,CoefficientBounds.b1701,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2078,CoefficientBounds.b2079,CoefficientBounds.b2080,CoefficientBounds.b2081,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2082,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2083,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds121 (r : Fin 102) : (boxes121 r).Contains (K.eval (column121 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2061
  · exact CoefficientBounds.sound2062
  · exact CoefficientBounds.sound2063
  · exact CoefficientBounds.sound2064
  · exact CoefficientBounds.sound2065
  · exact CoefficientBounds.sound2066
  · exact CoefficientBounds.sound2067
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2068
  · exact CoefficientBounds.sound2069
  · exact CoefficientBounds.sound2070
  · exact CoefficientBounds.sound2071
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2072
  · exact CoefficientBounds.sound2073
  · exact CoefficientBounds.sound2074
  · exact CoefficientBounds.sound1703
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2075
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2076
  · exact CoefficientBounds.sound2077
  · exact CoefficientBounds.sound2071
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1909
  · exact CoefficientBounds.sound1701
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2078
  · exact CoefficientBounds.sound2079
  · exact CoefficientBounds.sound2080
  · exact CoefficientBounds.sound2081
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2082
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2083
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column122 : Fin 102 → K := ![CoefficientBounds.p2084,CoefficientBounds.p2085,CoefficientBounds.p2086,CoefficientBounds.p2087,CoefficientBounds.p2088,CoefficientBounds.p2089,CoefficientBounds.p2090,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2091,CoefficientBounds.p2092,CoefficientBounds.p2093,CoefficientBounds.p2094,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2095,CoefficientBounds.p2096,CoefficientBounds.p1764,CoefficientBounds.p1548,CoefficientBounds.p1322,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2097,CoefficientBounds.p2098,CoefficientBounds.p1322,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1482,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2099,CoefficientBounds.p2100,CoefficientBounds.p2094,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1764,CoefficientBounds.p2101,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2102,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1235,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes122 : Fin 102 → Dyadic := ![CoefficientBounds.b2084,CoefficientBounds.b2085,CoefficientBounds.b2086,CoefficientBounds.b2087,CoefficientBounds.b2088,CoefficientBounds.b2089,CoefficientBounds.b2090,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2091,CoefficientBounds.b2092,CoefficientBounds.b2093,CoefficientBounds.b2094,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2095,CoefficientBounds.b2096,CoefficientBounds.b1764,CoefficientBounds.b1548,CoefficientBounds.b1322,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2097,CoefficientBounds.b2098,CoefficientBounds.b1322,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1482,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2099,CoefficientBounds.b2100,CoefficientBounds.b2094,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1764,CoefficientBounds.b2101,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2102,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1235,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds122 (r : Fin 102) : (boxes122 r).Contains (K.eval (column122 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2084
  · exact CoefficientBounds.sound2085
  · exact CoefficientBounds.sound2086
  · exact CoefficientBounds.sound2087
  · exact CoefficientBounds.sound2088
  · exact CoefficientBounds.sound2089
  · exact CoefficientBounds.sound2090
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2091
  · exact CoefficientBounds.sound2092
  · exact CoefficientBounds.sound2093
  · exact CoefficientBounds.sound2094
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2095
  · exact CoefficientBounds.sound2096
  · exact CoefficientBounds.sound1764
  · exact CoefficientBounds.sound1548
  · exact CoefficientBounds.sound1322
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2097
  · exact CoefficientBounds.sound2098
  · exact CoefficientBounds.sound1322
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1482
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2099
  · exact CoefficientBounds.sound2100
  · exact CoefficientBounds.sound2094
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1764
  · exact CoefficientBounds.sound2101
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2102
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1235
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column123 : Fin 102 → K := ![CoefficientBounds.p2103,CoefficientBounds.p2104,CoefficientBounds.p2105,CoefficientBounds.p2106,CoefficientBounds.p2107,CoefficientBounds.p2108,CoefficientBounds.p2109,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2110,CoefficientBounds.p2111,CoefficientBounds.p2112,CoefficientBounds.p2113,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2114,CoefficientBounds.p2115,CoefficientBounds.p2116,CoefficientBounds.p2117,CoefficientBounds.p2118,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2119,CoefficientBounds.p2120,CoefficientBounds.p2121,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2122,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2123,CoefficientBounds.p2124,CoefficientBounds.p2113,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1789,CoefficientBounds.p2125,CoefficientBounds.p1557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1583,CoefficientBounds.p1557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2126,CoefficientBounds.p2122,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p1585,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes123 : Fin 102 → Dyadic := ![CoefficientBounds.b2103,CoefficientBounds.b2104,CoefficientBounds.b2105,CoefficientBounds.b2106,CoefficientBounds.b2107,CoefficientBounds.b2108,CoefficientBounds.b2109,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2110,CoefficientBounds.b2111,CoefficientBounds.b2112,CoefficientBounds.b2113,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2114,CoefficientBounds.b2115,CoefficientBounds.b2116,CoefficientBounds.b2117,CoefficientBounds.b2118,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2119,CoefficientBounds.b2120,CoefficientBounds.b2121,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2122,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2123,CoefficientBounds.b2124,CoefficientBounds.b2113,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1789,CoefficientBounds.b2125,CoefficientBounds.b1557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1583,CoefficientBounds.b1557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2126,CoefficientBounds.b2122,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b1585,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds123 (r : Fin 102) : (boxes123 r).Contains (K.eval (column123 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2103
  · exact CoefficientBounds.sound2104
  · exact CoefficientBounds.sound2105
  · exact CoefficientBounds.sound2106
  · exact CoefficientBounds.sound2107
  · exact CoefficientBounds.sound2108
  · exact CoefficientBounds.sound2109
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2110
  · exact CoefficientBounds.sound2111
  · exact CoefficientBounds.sound2112
  · exact CoefficientBounds.sound2113
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2114
  · exact CoefficientBounds.sound2115
  · exact CoefficientBounds.sound2116
  · exact CoefficientBounds.sound2117
  · exact CoefficientBounds.sound2118
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2119
  · exact CoefficientBounds.sound2120
  · exact CoefficientBounds.sound2121
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2122
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2123
  · exact CoefficientBounds.sound2124
  · exact CoefficientBounds.sound2113
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1789
  · exact CoefficientBounds.sound2125
  · exact CoefficientBounds.sound1557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1583
  · exact CoefficientBounds.sound1557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2126
  · exact CoefficientBounds.sound2122
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1585
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column124 : Fin 102 → K := ![CoefficientBounds.p2127,CoefficientBounds.p2128,CoefficientBounds.p2129,CoefficientBounds.p2130,CoefficientBounds.p2131,CoefficientBounds.p2132,CoefficientBounds.p2133,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2134,CoefficientBounds.p2135,CoefficientBounds.p2136,CoefficientBounds.p2137,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2138,CoefficientBounds.p2139,CoefficientBounds.p1814,CoefficientBounds.p1597,CoefficientBounds.p1365,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2140,CoefficientBounds.p2141,CoefficientBounds.p2142,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2143,CoefficientBounds.p2144,CoefficientBounds.p2137,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1814,CoefficientBounds.p1600,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2145,CoefficientBounds.p1557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1988,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2146,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2147,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes124 : Fin 102 → Dyadic := ![CoefficientBounds.b2127,CoefficientBounds.b2128,CoefficientBounds.b2129,CoefficientBounds.b2130,CoefficientBounds.b2131,CoefficientBounds.b2132,CoefficientBounds.b2133,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2134,CoefficientBounds.b2135,CoefficientBounds.b2136,CoefficientBounds.b2137,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2138,CoefficientBounds.b2139,CoefficientBounds.b1814,CoefficientBounds.b1597,CoefficientBounds.b1365,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2140,CoefficientBounds.b2141,CoefficientBounds.b2142,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2143,CoefficientBounds.b2144,CoefficientBounds.b2137,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1814,CoefficientBounds.b1600,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2145,CoefficientBounds.b1557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1988,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2146,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2147,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds124 (r : Fin 102) : (boxes124 r).Contains (K.eval (column124 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2127
  · exact CoefficientBounds.sound2128
  · exact CoefficientBounds.sound2129
  · exact CoefficientBounds.sound2130
  · exact CoefficientBounds.sound2131
  · exact CoefficientBounds.sound2132
  · exact CoefficientBounds.sound2133
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2134
  · exact CoefficientBounds.sound2135
  · exact CoefficientBounds.sound2136
  · exact CoefficientBounds.sound2137
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2138
  · exact CoefficientBounds.sound2139
  · exact CoefficientBounds.sound1814
  · exact CoefficientBounds.sound1597
  · exact CoefficientBounds.sound1365
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2140
  · exact CoefficientBounds.sound2141
  · exact CoefficientBounds.sound2142
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2143
  · exact CoefficientBounds.sound2144
  · exact CoefficientBounds.sound2137
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1814
  · exact CoefficientBounds.sound1600
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2145
  · exact CoefficientBounds.sound1557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1988
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2146
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2147
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column125 : Fin 102 → K := ![CoefficientBounds.p2148,CoefficientBounds.p2149,CoefficientBounds.p2150,CoefficientBounds.p2151,CoefficientBounds.p2152,CoefficientBounds.p2153,CoefficientBounds.p2154,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2155,CoefficientBounds.p2156,CoefficientBounds.p2157,CoefficientBounds.p2158,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2159,CoefficientBounds.p2160,CoefficientBounds.p1836,CoefficientBounds.p1621,CoefficientBounds.p1385,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2161,CoefficientBounds.p1631,CoefficientBounds.p1385,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2162,CoefficientBounds.p2163,CoefficientBounds.p2164,CoefficientBounds.p2165,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2166,CoefficientBounds.p1836,CoefficientBounds.p1624,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1843,CoefficientBounds.p1632,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2008,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1633,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes125 : Fin 102 → Dyadic := ![CoefficientBounds.b2148,CoefficientBounds.b2149,CoefficientBounds.b2150,CoefficientBounds.b2151,CoefficientBounds.b2152,CoefficientBounds.b2153,CoefficientBounds.b2154,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2155,CoefficientBounds.b2156,CoefficientBounds.b2157,CoefficientBounds.b2158,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2159,CoefficientBounds.b2160,CoefficientBounds.b1836,CoefficientBounds.b1621,CoefficientBounds.b1385,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2161,CoefficientBounds.b1631,CoefficientBounds.b1385,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2162,CoefficientBounds.b2163,CoefficientBounds.b2164,CoefficientBounds.b2165,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2166,CoefficientBounds.b1836,CoefficientBounds.b1624,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1843,CoefficientBounds.b1632,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2008,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1633,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds125 (r : Fin 102) : (boxes125 r).Contains (K.eval (column125 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2148
  · exact CoefficientBounds.sound2149
  · exact CoefficientBounds.sound2150
  · exact CoefficientBounds.sound2151
  · exact CoefficientBounds.sound2152
  · exact CoefficientBounds.sound2153
  · exact CoefficientBounds.sound2154
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2155
  · exact CoefficientBounds.sound2156
  · exact CoefficientBounds.sound2157
  · exact CoefficientBounds.sound2158
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2159
  · exact CoefficientBounds.sound2160
  · exact CoefficientBounds.sound1836
  · exact CoefficientBounds.sound1621
  · exact CoefficientBounds.sound1385
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2161
  · exact CoefficientBounds.sound1631
  · exact CoefficientBounds.sound1385
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2162
  · exact CoefficientBounds.sound2163
  · exact CoefficientBounds.sound2164
  · exact CoefficientBounds.sound2165
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2166
  · exact CoefficientBounds.sound1836
  · exact CoefficientBounds.sound1624
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1843
  · exact CoefficientBounds.sound1632
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2008
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1633
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column126 : Fin 102 → K := ![CoefficientBounds.p2167,CoefficientBounds.p2168,CoefficientBounds.p2169,CoefficientBounds.p2170,CoefficientBounds.p2171,CoefficientBounds.p2172,CoefficientBounds.p2173,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2174,CoefficientBounds.p2175,CoefficientBounds.p2176,CoefficientBounds.p2177,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2178,CoefficientBounds.p2179,CoefficientBounds.p1856,CoefficientBounds.p1645,CoefficientBounds.p1406,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2180,CoefficientBounds.p2181,CoefficientBounds.p1406,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2182,CoefficientBounds.p2183,CoefficientBounds.p2184,CoefficientBounds.p2102,CoefficientBounds.p1771,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2185,CoefficientBounds.p2186,CoefficientBounds.p2187,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2188,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2189,CoefficientBounds.p2030,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1656,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes126 : Fin 102 → Dyadic := ![CoefficientBounds.b2167,CoefficientBounds.b2168,CoefficientBounds.b2169,CoefficientBounds.b2170,CoefficientBounds.b2171,CoefficientBounds.b2172,CoefficientBounds.b2173,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2174,CoefficientBounds.b2175,CoefficientBounds.b2176,CoefficientBounds.b2177,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2178,CoefficientBounds.b2179,CoefficientBounds.b1856,CoefficientBounds.b1645,CoefficientBounds.b1406,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2180,CoefficientBounds.b2181,CoefficientBounds.b1406,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2182,CoefficientBounds.b2183,CoefficientBounds.b2184,CoefficientBounds.b2102,CoefficientBounds.b1771,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2185,CoefficientBounds.b2186,CoefficientBounds.b2187,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2188,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2189,CoefficientBounds.b2030,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1656,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds126 (r : Fin 102) : (boxes126 r).Contains (K.eval (column126 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2167
  · exact CoefficientBounds.sound2168
  · exact CoefficientBounds.sound2169
  · exact CoefficientBounds.sound2170
  · exact CoefficientBounds.sound2171
  · exact CoefficientBounds.sound2172
  · exact CoefficientBounds.sound2173
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2174
  · exact CoefficientBounds.sound2175
  · exact CoefficientBounds.sound2176
  · exact CoefficientBounds.sound2177
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2178
  · exact CoefficientBounds.sound2179
  · exact CoefficientBounds.sound1856
  · exact CoefficientBounds.sound1645
  · exact CoefficientBounds.sound1406
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2180
  · exact CoefficientBounds.sound2181
  · exact CoefficientBounds.sound1406
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2182
  · exact CoefficientBounds.sound2183
  · exact CoefficientBounds.sound2184
  · exact CoefficientBounds.sound2102
  · exact CoefficientBounds.sound1771
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2185
  · exact CoefficientBounds.sound2186
  · exact CoefficientBounds.sound2187
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2188
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2189
  · exact CoefficientBounds.sound2030
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1656
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column127 : Fin 102 → K := ![CoefficientBounds.p2190,CoefficientBounds.p2191,CoefficientBounds.p2192,CoefficientBounds.p2193,CoefficientBounds.p2194,CoefficientBounds.p2195,CoefficientBounds.p2196,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2197,CoefficientBounds.p2198,CoefficientBounds.p2199,CoefficientBounds.p2200,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2201,CoefficientBounds.p2202,CoefficientBounds.p1878,CoefficientBounds.p1669,CoefficientBounds.p1427,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2203,CoefficientBounds.p1669,CoefficientBounds.p1427,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2204,CoefficientBounds.p2205,CoefficientBounds.p2200,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2206,CoefficientBounds.p2207,CoefficientBounds.p2122,CoefficientBounds.p2208,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2209,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2210,CoefficientBounds.p2211,CoefficientBounds.p2208,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1881,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes127 : Fin 102 → Dyadic := ![CoefficientBounds.b2190,CoefficientBounds.b2191,CoefficientBounds.b2192,CoefficientBounds.b2193,CoefficientBounds.b2194,CoefficientBounds.b2195,CoefficientBounds.b2196,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2197,CoefficientBounds.b2198,CoefficientBounds.b2199,CoefficientBounds.b2200,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2201,CoefficientBounds.b2202,CoefficientBounds.b1878,CoefficientBounds.b1669,CoefficientBounds.b1427,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2203,CoefficientBounds.b1669,CoefficientBounds.b1427,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2204,CoefficientBounds.b2205,CoefficientBounds.b2200,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2206,CoefficientBounds.b2207,CoefficientBounds.b2122,CoefficientBounds.b2208,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2209,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2210,CoefficientBounds.b2211,CoefficientBounds.b2208,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1881,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds127 (r : Fin 102) : (boxes127 r).Contains (K.eval (column127 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2190
  · exact CoefficientBounds.sound2191
  · exact CoefficientBounds.sound2192
  · exact CoefficientBounds.sound2193
  · exact CoefficientBounds.sound2194
  · exact CoefficientBounds.sound2195
  · exact CoefficientBounds.sound2196
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2197
  · exact CoefficientBounds.sound2198
  · exact CoefficientBounds.sound2199
  · exact CoefficientBounds.sound2200
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2201
  · exact CoefficientBounds.sound2202
  · exact CoefficientBounds.sound1878
  · exact CoefficientBounds.sound1669
  · exact CoefficientBounds.sound1427
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2203
  · exact CoefficientBounds.sound1669
  · exact CoefficientBounds.sound1427
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2204
  · exact CoefficientBounds.sound2205
  · exact CoefficientBounds.sound2200
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2206
  · exact CoefficientBounds.sound2207
  · exact CoefficientBounds.sound2122
  · exact CoefficientBounds.sound2208
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2209
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2210
  · exact CoefficientBounds.sound2211
  · exact CoefficientBounds.sound2208
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1881
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
