import Coulomb8.CoefficientBounds.B000
import Coulomb8.CoefficientBounds.B019
import Coulomb8.CoefficientBounds.B021
import Coulomb8.CoefficientBounds.B022
import Coulomb8.CoefficientBounds.B025
import Coulomb8.CoefficientBounds.B026
import Coulomb8.CoefficientBounds.B029
import Coulomb8.CoefficientBounds.B031
import Coulomb8.CoefficientBounds.B032
import Coulomb8.CoefficientBounds.B036
import Coulomb8.CoefficientBounds.B039
import Coulomb8.CoefficientBounds.B040
import Coulomb8.CoefficientBounds.B041
import Coulomb8.CoefficientBounds.B042
import Coulomb8.CoefficientBounds.B043

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Coulomb8.CoefficientMatrix

def column144 : Fin 102 → K := ![CoefficientBounds.p2545,CoefficientBounds.p2546,CoefficientBounds.p2547,CoefficientBounds.p2548,CoefficientBounds.p2549,CoefficientBounds.p2550,CoefficientBounds.p2551,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2552,CoefficientBounds.p2553,CoefficientBounds.p2554,CoefficientBounds.p2555,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2556,CoefficientBounds.p2550,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2557,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2558,CoefficientBounds.p2559,CoefficientBounds.p2560,CoefficientBounds.p2030,CoefficientBounds.p1656,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2561,CoefficientBounds.p2562,CoefficientBounds.p1656,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2563,CoefficientBounds.p0,CoefficientBounds.p1259,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1353,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes144 : Fin 102 → Dyadic := ![CoefficientBounds.b2545,CoefficientBounds.b2546,CoefficientBounds.b2547,CoefficientBounds.b2548,CoefficientBounds.b2549,CoefficientBounds.b2550,CoefficientBounds.b2551,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2552,CoefficientBounds.b2553,CoefficientBounds.b2554,CoefficientBounds.b2555,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2556,CoefficientBounds.b2550,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2557,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2558,CoefficientBounds.b2559,CoefficientBounds.b2560,CoefficientBounds.b2030,CoefficientBounds.b1656,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2561,CoefficientBounds.b2562,CoefficientBounds.b1656,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2563,CoefficientBounds.b0,CoefficientBounds.b1259,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1353,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds144 (r : Fin 102) : (boxes144 r).Contains (K.eval (column144 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2545
  · exact CoefficientBounds.sound2546
  · exact CoefficientBounds.sound2547
  · exact CoefficientBounds.sound2548
  · exact CoefficientBounds.sound2549
  · exact CoefficientBounds.sound2550
  · exact CoefficientBounds.sound2551
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2552
  · exact CoefficientBounds.sound2553
  · exact CoefficientBounds.sound2554
  · exact CoefficientBounds.sound2555
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2556
  · exact CoefficientBounds.sound2550
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2557
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2558
  · exact CoefficientBounds.sound2559
  · exact CoefficientBounds.sound2560
  · exact CoefficientBounds.sound2030
  · exact CoefficientBounds.sound1656
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2561
  · exact CoefficientBounds.sound2562
  · exact CoefficientBounds.sound1656
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2563
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1259
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1353
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column145 : Fin 102 → K := ![CoefficientBounds.p2564,CoefficientBounds.p2565,CoefficientBounds.p2566,CoefficientBounds.p2567,CoefficientBounds.p2568,CoefficientBounds.p2569,CoefficientBounds.p2570,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2571,CoefficientBounds.p2572,CoefficientBounds.p2573,CoefficientBounds.p2574,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2575,CoefficientBounds.p2569,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2576,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2577,CoefficientBounds.p2578,CoefficientBounds.p2579,CoefficientBounds.p2051,CoefficientBounds.p1881,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2580,CoefficientBounds.p2581,CoefficientBounds.p2582,CoefficientBounds.p2583,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2584,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2585,CoefficientBounds.p2586,CoefficientBounds.p2583,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2587,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes145 : Fin 102 → Dyadic := ![CoefficientBounds.b2564,CoefficientBounds.b2565,CoefficientBounds.b2566,CoefficientBounds.b2567,CoefficientBounds.b2568,CoefficientBounds.b2569,CoefficientBounds.b2570,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2571,CoefficientBounds.b2572,CoefficientBounds.b2573,CoefficientBounds.b2574,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2575,CoefficientBounds.b2569,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2576,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2577,CoefficientBounds.b2578,CoefficientBounds.b2579,CoefficientBounds.b2051,CoefficientBounds.b1881,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2580,CoefficientBounds.b2581,CoefficientBounds.b2582,CoefficientBounds.b2583,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2584,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2585,CoefficientBounds.b2586,CoefficientBounds.b2583,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2587,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds145 (r : Fin 102) : (boxes145 r).Contains (K.eval (column145 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2564
  · exact CoefficientBounds.sound2565
  · exact CoefficientBounds.sound2566
  · exact CoefficientBounds.sound2567
  · exact CoefficientBounds.sound2568
  · exact CoefficientBounds.sound2569
  · exact CoefficientBounds.sound2570
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2571
  · exact CoefficientBounds.sound2572
  · exact CoefficientBounds.sound2573
  · exact CoefficientBounds.sound2574
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2575
  · exact CoefficientBounds.sound2569
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2576
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2577
  · exact CoefficientBounds.sound2578
  · exact CoefficientBounds.sound2579
  · exact CoefficientBounds.sound2051
  · exact CoefficientBounds.sound1881
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2580
  · exact CoefficientBounds.sound2581
  · exact CoefficientBounds.sound2582
  · exact CoefficientBounds.sound2583
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2584
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2585
  · exact CoefficientBounds.sound2586
  · exact CoefficientBounds.sound2583
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2587
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column146 : Fin 102 → K := ![CoefficientBounds.p2588,CoefficientBounds.p2589,CoefficientBounds.p2590,CoefficientBounds.p2591,CoefficientBounds.p2592,CoefficientBounds.p2593,CoefficientBounds.p2594,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2595,CoefficientBounds.p2596,CoefficientBounds.p2597,CoefficientBounds.p2598,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2599,CoefficientBounds.p2593,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2600,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2601,CoefficientBounds.p2602,CoefficientBounds.p2603,CoefficientBounds.p2074,CoefficientBounds.p1703,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2604,CoefficientBounds.p1460,CoefficientBounds.p1703,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2605,CoefficientBounds.p2606,CoefficientBounds.p2607,CoefficientBounds.p2608,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2609,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2083,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes146 : Fin 102 → Dyadic := ![CoefficientBounds.b2588,CoefficientBounds.b2589,CoefficientBounds.b2590,CoefficientBounds.b2591,CoefficientBounds.b2592,CoefficientBounds.b2593,CoefficientBounds.b2594,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2595,CoefficientBounds.b2596,CoefficientBounds.b2597,CoefficientBounds.b2598,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2599,CoefficientBounds.b2593,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2600,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2601,CoefficientBounds.b2602,CoefficientBounds.b2603,CoefficientBounds.b2074,CoefficientBounds.b1703,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2604,CoefficientBounds.b1460,CoefficientBounds.b1703,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2605,CoefficientBounds.b2606,CoefficientBounds.b2607,CoefficientBounds.b2608,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2609,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2083,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds146 (r : Fin 102) : (boxes146 r).Contains (K.eval (column146 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2588
  · exact CoefficientBounds.sound2589
  · exact CoefficientBounds.sound2590
  · exact CoefficientBounds.sound2591
  · exact CoefficientBounds.sound2592
  · exact CoefficientBounds.sound2593
  · exact CoefficientBounds.sound2594
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2595
  · exact CoefficientBounds.sound2596
  · exact CoefficientBounds.sound2597
  · exact CoefficientBounds.sound2598
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2599
  · exact CoefficientBounds.sound2593
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2600
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2601
  · exact CoefficientBounds.sound2602
  · exact CoefficientBounds.sound2603
  · exact CoefficientBounds.sound2074
  · exact CoefficientBounds.sound1703
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2604
  · exact CoefficientBounds.sound1460
  · exact CoefficientBounds.sound1703
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2605
  · exact CoefficientBounds.sound2606
  · exact CoefficientBounds.sound2607
  · exact CoefficientBounds.sound2608
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2609
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2083
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column147 : Fin 102 → K := ![CoefficientBounds.p2610,CoefficientBounds.p2611,CoefficientBounds.p2612,CoefficientBounds.p2613,CoefficientBounds.p2614,CoefficientBounds.p2615,CoefficientBounds.p2616,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2617,CoefficientBounds.p2618,CoefficientBounds.p2619,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2620,CoefficientBounds.p2615,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2621,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2622,CoefficientBounds.p2623,CoefficientBounds.p2330,CoefficientBounds.p2624,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2625,CoefficientBounds.p2330,CoefficientBounds.p2624,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p1441,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2083,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes147 : Fin 102 → Dyadic := ![CoefficientBounds.b2610,CoefficientBounds.b2611,CoefficientBounds.b2612,CoefficientBounds.b2613,CoefficientBounds.b2614,CoefficientBounds.b2615,CoefficientBounds.b2616,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2617,CoefficientBounds.b2618,CoefficientBounds.b2619,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2620,CoefficientBounds.b2615,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2621,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2622,CoefficientBounds.b2623,CoefficientBounds.b2330,CoefficientBounds.b2624,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2625,CoefficientBounds.b2330,CoefficientBounds.b2624,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b1441,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2083,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds147 (r : Fin 102) : (boxes147 r).Contains (K.eval (column147 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2610
  · exact CoefficientBounds.sound2611
  · exact CoefficientBounds.sound2612
  · exact CoefficientBounds.sound2613
  · exact CoefficientBounds.sound2614
  · exact CoefficientBounds.sound2615
  · exact CoefficientBounds.sound2616
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2617
  · exact CoefficientBounds.sound2618
  · exact CoefficientBounds.sound2619
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2620
  · exact CoefficientBounds.sound2615
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2621
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2622
  · exact CoefficientBounds.sound2623
  · exact CoefficientBounds.sound2330
  · exact CoefficientBounds.sound2624
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2625
  · exact CoefficientBounds.sound2330
  · exact CoefficientBounds.sound2624
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound1441
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2083
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column148 : Fin 102 → K := ![CoefficientBounds.p2626,CoefficientBounds.p2627,CoefficientBounds.p2628,CoefficientBounds.p2629,CoefficientBounds.p2630,CoefficientBounds.p2631,CoefficientBounds.p2632,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2633,CoefficientBounds.p2634,CoefficientBounds.p2635,CoefficientBounds.p2636,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2637,CoefficientBounds.p2631,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2638,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2639,CoefficientBounds.p2640,CoefficientBounds.p2636,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2641,CoefficientBounds.p2604,CoefficientBounds.p2354,CoefficientBounds.p2642,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2643,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2644,CoefficientBounds.p2645,CoefficientBounds.p2646,CoefficientBounds.p2647,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2648,CoefficientBounds.p0,CoefficientBounds.p0]
def boxes148 : Fin 102 → Dyadic := ![CoefficientBounds.b2626,CoefficientBounds.b2627,CoefficientBounds.b2628,CoefficientBounds.b2629,CoefficientBounds.b2630,CoefficientBounds.b2631,CoefficientBounds.b2632,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2633,CoefficientBounds.b2634,CoefficientBounds.b2635,CoefficientBounds.b2636,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2637,CoefficientBounds.b2631,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2638,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2639,CoefficientBounds.b2640,CoefficientBounds.b2636,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2641,CoefficientBounds.b2604,CoefficientBounds.b2354,CoefficientBounds.b2642,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2643,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2644,CoefficientBounds.b2645,CoefficientBounds.b2646,CoefficientBounds.b2647,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2648,CoefficientBounds.b0,CoefficientBounds.b0]
theorem bounds148 (r : Fin 102) : (boxes148 r).Contains (K.eval (column148 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2626
  · exact CoefficientBounds.sound2627
  · exact CoefficientBounds.sound2628
  · exact CoefficientBounds.sound2629
  · exact CoefficientBounds.sound2630
  · exact CoefficientBounds.sound2631
  · exact CoefficientBounds.sound2632
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2633
  · exact CoefficientBounds.sound2634
  · exact CoefficientBounds.sound2635
  · exact CoefficientBounds.sound2636
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2637
  · exact CoefficientBounds.sound2631
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2638
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2639
  · exact CoefficientBounds.sound2640
  · exact CoefficientBounds.sound2636
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2641
  · exact CoefficientBounds.sound2604
  · exact CoefficientBounds.sound2354
  · exact CoefficientBounds.sound2642
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2643
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2644
  · exact CoefficientBounds.sound2645
  · exact CoefficientBounds.sound2646
  · exact CoefficientBounds.sound2647
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2648
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0

def column149 : Fin 102 → K := ![CoefficientBounds.p2649,CoefficientBounds.p2650,CoefficientBounds.p2651,CoefficientBounds.p2652,CoefficientBounds.p2653,CoefficientBounds.p2654,CoefficientBounds.p2655,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2656,CoefficientBounds.p2657,CoefficientBounds.p2658,CoefficientBounds.p2659,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2660,CoefficientBounds.p2654,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2661,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2662,CoefficientBounds.p2663,CoefficientBounds.p2659,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2664,CoefficientBounds.p2665,CoefficientBounds.p2666,CoefficientBounds.p2667,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2668,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2648]
def boxes149 : Fin 102 → Dyadic := ![CoefficientBounds.b2649,CoefficientBounds.b2650,CoefficientBounds.b2651,CoefficientBounds.b2652,CoefficientBounds.b2653,CoefficientBounds.b2654,CoefficientBounds.b2655,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2656,CoefficientBounds.b2657,CoefficientBounds.b2658,CoefficientBounds.b2659,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2660,CoefficientBounds.b2654,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2661,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2662,CoefficientBounds.b2663,CoefficientBounds.b2659,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2664,CoefficientBounds.b2665,CoefficientBounds.b2666,CoefficientBounds.b2667,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2668,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2648]
theorem bounds149 (r : Fin 102) : (boxes149 r).Contains (K.eval (column149 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2649
  · exact CoefficientBounds.sound2650
  · exact CoefficientBounds.sound2651
  · exact CoefficientBounds.sound2652
  · exact CoefficientBounds.sound2653
  · exact CoefficientBounds.sound2654
  · exact CoefficientBounds.sound2655
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2656
  · exact CoefficientBounds.sound2657
  · exact CoefficientBounds.sound2658
  · exact CoefficientBounds.sound2659
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2660
  · exact CoefficientBounds.sound2654
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2661
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2662
  · exact CoefficientBounds.sound2663
  · exact CoefficientBounds.sound2659
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2664
  · exact CoefficientBounds.sound2665
  · exact CoefficientBounds.sound2666
  · exact CoefficientBounds.sound2667
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2668
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2648

def column150 : Fin 102 → K := ![CoefficientBounds.p2669,CoefficientBounds.p2670,CoefficientBounds.p2671,CoefficientBounds.p2672,CoefficientBounds.p2673,CoefficientBounds.p2674,CoefficientBounds.p2675,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2676,CoefficientBounds.p2677,CoefficientBounds.p2678,CoefficientBounds.p2679,CoefficientBounds.p2680,CoefficientBounds.p2681,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2682,CoefficientBounds.p2683,CoefficientBounds.p2684,CoefficientBounds.p2685,CoefficientBounds.p2686,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2687,CoefficientBounds.p2688,CoefficientBounds.p2689,CoefficientBounds.p2690,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2691,CoefficientBounds.p2692,CoefficientBounds.p2693,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2694,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2695,CoefficientBounds.p2696,CoefficientBounds.p2697,CoefficientBounds.p2698,CoefficientBounds.p2699,CoefficientBounds.p2700,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2701,CoefficientBounds.p2702,CoefficientBounds.p2703,CoefficientBounds.p2704,CoefficientBounds.p2705,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2706,CoefficientBounds.p2707,CoefficientBounds.p2708,CoefficientBounds.p2709,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2710,CoefficientBounds.p2711,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2712,CoefficientBounds.p2713,CoefficientBounds.p2714,CoefficientBounds.p2715,CoefficientBounds.p2716,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2717,CoefficientBounds.p2718,CoefficientBounds.p2719,CoefficientBounds.p2720,CoefficientBounds.p0,CoefficientBounds.p2721,CoefficientBounds.p2722,CoefficientBounds.p2723,CoefficientBounds.p2724,CoefficientBounds.p2725,CoefficientBounds.p2726,CoefficientBounds.p2727,CoefficientBounds.p2728,CoefficientBounds.p2729,CoefficientBounds.p2730,CoefficientBounds.p2731]
def boxes150 : Fin 102 → Dyadic := ![CoefficientBounds.b2669,CoefficientBounds.b2670,CoefficientBounds.b2671,CoefficientBounds.b2672,CoefficientBounds.b2673,CoefficientBounds.b2674,CoefficientBounds.b2675,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2676,CoefficientBounds.b2677,CoefficientBounds.b2678,CoefficientBounds.b2679,CoefficientBounds.b2680,CoefficientBounds.b2681,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2682,CoefficientBounds.b2683,CoefficientBounds.b2684,CoefficientBounds.b2685,CoefficientBounds.b2686,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2687,CoefficientBounds.b2688,CoefficientBounds.b2689,CoefficientBounds.b2690,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2691,CoefficientBounds.b2692,CoefficientBounds.b2693,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2694,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2695,CoefficientBounds.b2696,CoefficientBounds.b2697,CoefficientBounds.b2698,CoefficientBounds.b2699,CoefficientBounds.b2700,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2701,CoefficientBounds.b2702,CoefficientBounds.b2703,CoefficientBounds.b2704,CoefficientBounds.b2705,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2706,CoefficientBounds.b2707,CoefficientBounds.b2708,CoefficientBounds.b2709,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2710,CoefficientBounds.b2711,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2712,CoefficientBounds.b2713,CoefficientBounds.b2714,CoefficientBounds.b2715,CoefficientBounds.b2716,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2717,CoefficientBounds.b2718,CoefficientBounds.b2719,CoefficientBounds.b2720,CoefficientBounds.b0,CoefficientBounds.b2721,CoefficientBounds.b2722,CoefficientBounds.b2723,CoefficientBounds.b2724,CoefficientBounds.b2725,CoefficientBounds.b2726,CoefficientBounds.b2727,CoefficientBounds.b2728,CoefficientBounds.b2729,CoefficientBounds.b2730,CoefficientBounds.b2731]
theorem bounds150 (r : Fin 102) : (boxes150 r).Contains (K.eval (column150 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2669
  · exact CoefficientBounds.sound2670
  · exact CoefficientBounds.sound2671
  · exact CoefficientBounds.sound2672
  · exact CoefficientBounds.sound2673
  · exact CoefficientBounds.sound2674
  · exact CoefficientBounds.sound2675
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2676
  · exact CoefficientBounds.sound2677
  · exact CoefficientBounds.sound2678
  · exact CoefficientBounds.sound2679
  · exact CoefficientBounds.sound2680
  · exact CoefficientBounds.sound2681
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2682
  · exact CoefficientBounds.sound2683
  · exact CoefficientBounds.sound2684
  · exact CoefficientBounds.sound2685
  · exact CoefficientBounds.sound2686
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2687
  · exact CoefficientBounds.sound2688
  · exact CoefficientBounds.sound2689
  · exact CoefficientBounds.sound2690
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2691
  · exact CoefficientBounds.sound2692
  · exact CoefficientBounds.sound2693
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2694
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2695
  · exact CoefficientBounds.sound2696
  · exact CoefficientBounds.sound2697
  · exact CoefficientBounds.sound2698
  · exact CoefficientBounds.sound2699
  · exact CoefficientBounds.sound2700
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2701
  · exact CoefficientBounds.sound2702
  · exact CoefficientBounds.sound2703
  · exact CoefficientBounds.sound2704
  · exact CoefficientBounds.sound2705
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2706
  · exact CoefficientBounds.sound2707
  · exact CoefficientBounds.sound2708
  · exact CoefficientBounds.sound2709
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2710
  · exact CoefficientBounds.sound2711
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2712
  · exact CoefficientBounds.sound2713
  · exact CoefficientBounds.sound2714
  · exact CoefficientBounds.sound2715
  · exact CoefficientBounds.sound2716
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2717
  · exact CoefficientBounds.sound2718
  · exact CoefficientBounds.sound2719
  · exact CoefficientBounds.sound2720
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2721
  · exact CoefficientBounds.sound2722
  · exact CoefficientBounds.sound2723
  · exact CoefficientBounds.sound2724
  · exact CoefficientBounds.sound2725
  · exact CoefficientBounds.sound2726
  · exact CoefficientBounds.sound2727
  · exact CoefficientBounds.sound2728
  · exact CoefficientBounds.sound2729
  · exact CoefficientBounds.sound2730
  · exact CoefficientBounds.sound2731

def column151 : Fin 102 → K := ![CoefficientBounds.p2732,CoefficientBounds.p2733,CoefficientBounds.p2734,CoefficientBounds.p2735,CoefficientBounds.p2736,CoefficientBounds.p2737,CoefficientBounds.p2738,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2739,CoefficientBounds.p2740,CoefficientBounds.p2741,CoefficientBounds.p2742,CoefficientBounds.p2743,CoefficientBounds.p2744,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2745,CoefficientBounds.p2746,CoefficientBounds.p2747,CoefficientBounds.p2748,CoefficientBounds.p2749,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2750,CoefficientBounds.p2751,CoefficientBounds.p2752,CoefficientBounds.p2753,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2754,CoefficientBounds.p2755,CoefficientBounds.p2756,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2757,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2758,CoefficientBounds.p2759,CoefficientBounds.p2760,CoefficientBounds.p2761,CoefficientBounds.p2762,CoefficientBounds.p2763,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2764,CoefficientBounds.p2765,CoefficientBounds.p2766,CoefficientBounds.p2767,CoefficientBounds.p2768,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2769,CoefficientBounds.p2770,CoefficientBounds.p2771,CoefficientBounds.p2772,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2773,CoefficientBounds.p2774,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2775,CoefficientBounds.p2776,CoefficientBounds.p2777,CoefficientBounds.p2778,CoefficientBounds.p2779,CoefficientBounds.p0,CoefficientBounds.p0,CoefficientBounds.p2780,CoefficientBounds.p2781,CoefficientBounds.p2782,CoefficientBounds.p2783,CoefficientBounds.p0,CoefficientBounds.p2784,CoefficientBounds.p2785,CoefficientBounds.p2786,CoefficientBounds.p2787,CoefficientBounds.p2788,CoefficientBounds.p2789,CoefficientBounds.p2790,CoefficientBounds.p2791,CoefficientBounds.p2792,CoefficientBounds.p2793,CoefficientBounds.p0]
def boxes151 : Fin 102 → Dyadic := ![CoefficientBounds.b2732,CoefficientBounds.b2733,CoefficientBounds.b2734,CoefficientBounds.b2735,CoefficientBounds.b2736,CoefficientBounds.b2737,CoefficientBounds.b2738,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2739,CoefficientBounds.b2740,CoefficientBounds.b2741,CoefficientBounds.b2742,CoefficientBounds.b2743,CoefficientBounds.b2744,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2745,CoefficientBounds.b2746,CoefficientBounds.b2747,CoefficientBounds.b2748,CoefficientBounds.b2749,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2750,CoefficientBounds.b2751,CoefficientBounds.b2752,CoefficientBounds.b2753,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2754,CoefficientBounds.b2755,CoefficientBounds.b2756,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2757,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2758,CoefficientBounds.b2759,CoefficientBounds.b2760,CoefficientBounds.b2761,CoefficientBounds.b2762,CoefficientBounds.b2763,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2764,CoefficientBounds.b2765,CoefficientBounds.b2766,CoefficientBounds.b2767,CoefficientBounds.b2768,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2769,CoefficientBounds.b2770,CoefficientBounds.b2771,CoefficientBounds.b2772,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2773,CoefficientBounds.b2774,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2775,CoefficientBounds.b2776,CoefficientBounds.b2777,CoefficientBounds.b2778,CoefficientBounds.b2779,CoefficientBounds.b0,CoefficientBounds.b0,CoefficientBounds.b2780,CoefficientBounds.b2781,CoefficientBounds.b2782,CoefficientBounds.b2783,CoefficientBounds.b0,CoefficientBounds.b2784,CoefficientBounds.b2785,CoefficientBounds.b2786,CoefficientBounds.b2787,CoefficientBounds.b2788,CoefficientBounds.b2789,CoefficientBounds.b2790,CoefficientBounds.b2791,CoefficientBounds.b2792,CoefficientBounds.b2793,CoefficientBounds.b0]
theorem bounds151 (r : Fin 102) : (boxes151 r).Contains (K.eval (column151 r)) := by
  fin_cases r
  · exact CoefficientBounds.sound2732
  · exact CoefficientBounds.sound2733
  · exact CoefficientBounds.sound2734
  · exact CoefficientBounds.sound2735
  · exact CoefficientBounds.sound2736
  · exact CoefficientBounds.sound2737
  · exact CoefficientBounds.sound2738
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2739
  · exact CoefficientBounds.sound2740
  · exact CoefficientBounds.sound2741
  · exact CoefficientBounds.sound2742
  · exact CoefficientBounds.sound2743
  · exact CoefficientBounds.sound2744
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2745
  · exact CoefficientBounds.sound2746
  · exact CoefficientBounds.sound2747
  · exact CoefficientBounds.sound2748
  · exact CoefficientBounds.sound2749
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2750
  · exact CoefficientBounds.sound2751
  · exact CoefficientBounds.sound2752
  · exact CoefficientBounds.sound2753
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2754
  · exact CoefficientBounds.sound2755
  · exact CoefficientBounds.sound2756
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2757
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2758
  · exact CoefficientBounds.sound2759
  · exact CoefficientBounds.sound2760
  · exact CoefficientBounds.sound2761
  · exact CoefficientBounds.sound2762
  · exact CoefficientBounds.sound2763
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2764
  · exact CoefficientBounds.sound2765
  · exact CoefficientBounds.sound2766
  · exact CoefficientBounds.sound2767
  · exact CoefficientBounds.sound2768
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2769
  · exact CoefficientBounds.sound2770
  · exact CoefficientBounds.sound2771
  · exact CoefficientBounds.sound2772
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2773
  · exact CoefficientBounds.sound2774
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2775
  · exact CoefficientBounds.sound2776
  · exact CoefficientBounds.sound2777
  · exact CoefficientBounds.sound2778
  · exact CoefficientBounds.sound2779
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2780
  · exact CoefficientBounds.sound2781
  · exact CoefficientBounds.sound2782
  · exact CoefficientBounds.sound2783
  · exact CoefficientBounds.sound0
  · exact CoefficientBounds.sound2784
  · exact CoefficientBounds.sound2785
  · exact CoefficientBounds.sound2786
  · exact CoefficientBounds.sound2787
  · exact CoefficientBounds.sound2788
  · exact CoefficientBounds.sound2789
  · exact CoefficientBounds.sound2790
  · exact CoefficientBounds.sound2791
  · exact CoefficientBounds.sound2792
  · exact CoefficientBounds.sound2793
  · exact CoefficientBounds.sound0

end Coulomb8.CoefficientMatrix
